// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO dagu_dag_run_attempts (
    id,
    run_id,
    dag_name,
    dag_run_id,
    root_dag_name,
    root_dag_run_id,
    is_root,
    attempt_id,
    run_created_at,
    attempt_created_at,
    workspace,
    workspace_valid,
    data,
    local_work_dir
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, run_id, dag_name, dag_run_id, root_dag_name, root_dag_run_id, is_root, attempt_id, run_created_at, attempt_created_at, workspace, workspace_valid, status, started_at, finished_at, data_version, data, cancel_requested, hidden, local_work_dir, created_at, updated_at
`

type CreateAttemptParams struct {
	ID               uuid.UUID          `json:"id"`
	RunID            uuid.UUID          `json:"run_id"`
	DagName          string             `json:"dag_name"`
	DagRunID         string             `json:"dag_run_id"`
	RootDagName      string             `json:"root_dag_name"`
	RootDagRunID     string             `json:"root_dag_run_id"`
	IsRoot           bool               `json:"is_root"`
	AttemptID        string             `json:"attempt_id"`
	RunCreatedAt     pgtype.Timestamptz `json:"run_created_at"`
	AttemptCreatedAt pgtype.Timestamptz `json:"attempt_created_at"`
	Workspace        sql.NullString     `json:"workspace"`
	WorkspaceValid   bool               `json:"workspace_valid"`
	Data             []byte             `json:"data"`
	LocalWorkDir     string             `json:"local_work_dir"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (DaguDagRunAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.RunID,
		arg.DagName,
		arg.DagRunID,
		arg.RootDagName,
		arg.RootDagRunID,
		arg.IsRoot,
		arg.AttemptID,
		arg.RunCreatedAt,
		arg.AttemptCreatedAt,
		arg.Workspace,
		arg.WorkspaceValid,
		arg.Data,
		arg.LocalWorkDir,
	)
	var i DaguDagRunAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.AttemptID,
		&i.RunCreatedAt,
		&i.AttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CancelRequested,
		&i.Hidden,
		&i.LocalWorkDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO dagu_dag_runs (
    id,
    dag_name,
    dag_run_id,
    root_dag_name,
    root_dag_run_id,
    is_root,
    run_created_at,
    workspace,
    workspace_valid
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, dag_name, dag_run_id, root_dag_name, root_dag_run_id, is_root, run_created_at, latest_attempt_id, latest_attempt_created_at, workspace, workspace_valid, status, started_at, finished_at, data_version, data, created_at, updated_at
`

type CreateRunParams struct {
	ID             uuid.UUID          `json:"id"`
	DagName        string             `json:"dag_name"`
	DagRunID       string             `json:"dag_run_id"`
	RootDagName    string             `json:"root_dag_name"`
	RootDagRunID   string             `json:"root_dag_run_id"`
	IsRoot         bool               `json:"is_root"`
	RunCreatedAt   pgtype.Timestamptz `json:"run_created_at"`
	Workspace      sql.NullString     `json:"workspace"`
	WorkspaceValid bool               `json:"workspace_valid"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (DaguDagRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.DagName,
		arg.DagRunID,
		arg.RootDagName,
		arg.RootDagRunID,
		arg.IsRoot,
		arg.RunCreatedAt,
		arg.Workspace,
		arg.WorkspaceValid,
	)
	var i DaguDagRun
	err := row.Scan(
		&i.ID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.RunCreatedAt,
		&i.LatestAttemptID,
		&i.LatestAttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDAGRunRows = `-- name: DeleteDAGRunRows :many
WITH root_run AS (
    SELECT r.id
    FROM dagu_dag_runs AS r
    WHERE r.is_root
      AND r.dag_name = $1
      AND r.dag_run_id = $2
),
doomed AS (
    SELECT r.id, r.dag_run_id
    FROM dagu_dag_runs AS r
    WHERE r.id IN (SELECT id FROM root_run)
       OR (
           r.root_dag_name = $1
           AND r.root_dag_run_id = $2
       )
),
deleted AS (
    DELETE FROM dagu_dag_runs AS r
    WHERE r.id IN (SELECT id FROM doomed)
)
SELECT DISTINCT dag_run_id
FROM doomed
ORDER BY dag_run_id
`

type DeleteDAGRunRowsParams struct {
	RootDagName  string `json:"root_dag_name"`
	RootDagRunID string `json:"root_dag_run_id"`
}

func (q *Queries) DeleteDAGRunRows(ctx context.Context, arg DeleteDAGRunRowsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteDAGRunRows, arg.RootDagName, arg.RootDagRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dag_run_id string
		if err := rows.Scan(&dag_run_id); err != nil {
			return nil, err
		}
		items = append(items, dag_run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRootRun = `-- name: FindRootRun :one
SELECT id, dag_name, dag_run_id, root_dag_name, root_dag_run_id, is_root, run_created_at, latest_attempt_id, latest_attempt_created_at, workspace, workspace_valid, status, started_at, finished_at, data_version, data, created_at, updated_at
FROM dagu_dag_runs
WHERE is_root
  AND dag_name = $1
  AND dag_run_id = $2
LIMIT 1
`

type FindRootRunParams struct {
	DagName  string `json:"dag_name"`
	DagRunID string `json:"dag_run_id"`
}

func (q *Queries) FindRootRun(ctx context.Context, arg FindRootRunParams) (DaguDagRun, error) {
	row := q.db.QueryRow(ctx, findRootRun, arg.DagName, arg.DagRunID)
	var i DaguDagRun
	err := row.Scan(
		&i.ID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.RunCreatedAt,
		&i.LatestAttemptID,
		&i.LatestAttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSubRun = `-- name: FindSubRun :one
SELECT id, dag_name, dag_run_id, root_dag_name, root_dag_run_id, is_root, run_created_at, latest_attempt_id, latest_attempt_created_at, workspace, workspace_valid, status, started_at, finished_at, data_version, data, created_at, updated_at
FROM dagu_dag_runs
WHERE NOT is_root
  AND root_dag_name = $1
  AND root_dag_run_id = $2
  AND dag_run_id = $3
LIMIT 1
`

type FindSubRunParams struct {
	RootDagName  string `json:"root_dag_name"`
	RootDagRunID string `json:"root_dag_run_id"`
	DagRunID     string `json:"dag_run_id"`
}

func (q *Queries) FindSubRun(ctx context.Context, arg FindSubRunParams) (DaguDagRun, error) {
	row := q.db.QueryRow(ctx, findSubRun, arg.RootDagName, arg.RootDagRunID, arg.DagRunID)
	var i DaguDagRun
	err := row.Scan(
		&i.ID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.RunCreatedAt,
		&i.LatestAttemptID,
		&i.LatestAttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, run_id, dag_name, dag_run_id, root_dag_name, root_dag_run_id, is_root, attempt_id, run_created_at, attempt_created_at, workspace, workspace_valid, status, started_at, finished_at, data_version, data, cancel_requested, hidden, local_work_dir, created_at, updated_at
FROM dagu_dag_run_attempts
WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id uuid.UUID) (DaguDagRunAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i DaguDagRunAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.AttemptID,
		&i.RunCreatedAt,
		&i.AttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CancelRequested,
		&i.Hidden,
		&i.LocalWorkDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestAttemptByName = `-- name: LatestAttemptByName :one
SELECT a.id, a.run_id, a.dag_name, a.dag_run_id, a.root_dag_name, a.root_dag_run_id, a.is_root, a.attempt_id, a.run_created_at, a.attempt_created_at, a.workspace, a.workspace_valid, a.status, a.started_at, a.finished_at, a.data_version, a.data, a.cancel_requested, a.hidden, a.local_work_dir, a.created_at, a.updated_at
FROM dagu_dag_runs r
JOIN dagu_dag_run_attempts a ON a.id = r.latest_attempt_id
WHERE r.is_root
  AND r.dag_name = $1
  AND r.data ? 'status'
  AND NOT a.hidden
  AND (NOT $2::boolean OR r.run_created_at >= $3::timestamptz)
ORDER BY r.run_created_at DESC, r.dag_run_id ASC
LIMIT 1
`

type LatestAttemptByNameParams struct {
	DagName string             `json:"dag_name"`
	HasFrom bool               `json:"has_from"`
	FromAt  pgtype.Timestamptz `json:"from_at"`
}

func (q *Queries) LatestAttemptByName(ctx context.Context, arg LatestAttemptByNameParams) (DaguDagRunAttempt, error) {
	row := q.db.QueryRow(ctx, latestAttemptByName, arg.DagName, arg.HasFrom, arg.FromAt)
	var i DaguDagRunAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.AttemptID,
		&i.RunCreatedAt,
		&i.AttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CancelRequested,
		&i.Hidden,
		&i.LocalWorkDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestRootAttempt = `-- name: LatestRootAttempt :one
SELECT a.id, a.run_id, a.dag_name, a.dag_run_id, a.root_dag_name, a.root_dag_run_id, a.is_root, a.attempt_id, a.run_created_at, a.attempt_created_at, a.workspace, a.workspace_valid, a.status, a.started_at, a.finished_at, a.data_version, a.data, a.cancel_requested, a.hidden, a.local_work_dir, a.created_at, a.updated_at
FROM dagu_dag_runs r
JOIN dagu_dag_run_attempts a ON a.id = r.latest_attempt_id
WHERE r.is_root
  AND r.dag_name = $1
  AND r.dag_run_id = $2
  AND r.data ? 'status'
  AND NOT a.hidden
LIMIT 1
`

type LatestRootAttemptParams struct {
	DagName  string `json:"dag_name"`
	DagRunID string `json:"dag_run_id"`
}

func (q *Queries) LatestRootAttempt(ctx context.Context, arg LatestRootAttemptParams) (DaguDagRunAttempt, error) {
	row := q.db.QueryRow(ctx, latestRootAttempt, arg.DagName, arg.DagRunID)
	var i DaguDagRunAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.AttemptID,
		&i.RunCreatedAt,
		&i.AttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CancelRequested,
		&i.Hidden,
		&i.LocalWorkDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestRootAttemptForUpdate = `-- name: LatestRootAttemptForUpdate :one
SELECT a.id, a.run_id, a.dag_name, a.dag_run_id, a.root_dag_name, a.root_dag_run_id, a.is_root, a.attempt_id, a.run_created_at, a.attempt_created_at, a.workspace, a.workspace_valid, a.status, a.started_at, a.finished_at, a.data_version, a.data, a.cancel_requested, a.hidden, a.local_work_dir, a.created_at, a.updated_at
FROM dagu_dag_runs r
JOIN dagu_dag_run_attempts a ON a.id = r.latest_attempt_id
WHERE r.is_root
  AND r.dag_name = $1
  AND r.dag_run_id = $2
  AND r.data ? 'status'
  AND NOT a.hidden
LIMIT 1
FOR UPDATE OF r, a
`

type LatestRootAttemptForUpdateParams struct {
	DagName  string `json:"dag_name"`
	DagRunID string `json:"dag_run_id"`
}

func (q *Queries) LatestRootAttemptForUpdate(ctx context.Context, arg LatestRootAttemptForUpdateParams) (DaguDagRunAttempt, error) {
	row := q.db.QueryRow(ctx, latestRootAttemptForUpdate, arg.DagName, arg.DagRunID)
	var i DaguDagRunAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.AttemptID,
		&i.RunCreatedAt,
		&i.AttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CancelRequested,
		&i.Hidden,
		&i.LocalWorkDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestSubAttempt = `-- name: LatestSubAttempt :one
SELECT a.id, a.run_id, a.dag_name, a.dag_run_id, a.root_dag_name, a.root_dag_run_id, a.is_root, a.attempt_id, a.run_created_at, a.attempt_created_at, a.workspace, a.workspace_valid, a.status, a.started_at, a.finished_at, a.data_version, a.data, a.cancel_requested, a.hidden, a.local_work_dir, a.created_at, a.updated_at
FROM dagu_dag_runs r
JOIN dagu_dag_run_attempts a ON a.id = r.latest_attempt_id
WHERE NOT r.is_root
  AND r.root_dag_name = $1
  AND r.root_dag_run_id = $2
  AND r.dag_run_id = $3
  AND r.data ? 'status'
  AND NOT a.hidden
LIMIT 1
`

type LatestSubAttemptParams struct {
	RootDagName  string `json:"root_dag_name"`
	RootDagRunID string `json:"root_dag_run_id"`
	DagRunID     string `json:"dag_run_id"`
}

func (q *Queries) LatestSubAttempt(ctx context.Context, arg LatestSubAttemptParams) (DaguDagRunAttempt, error) {
	row := q.db.QueryRow(ctx, latestSubAttempt, arg.RootDagName, arg.RootDagRunID, arg.DagRunID)
	var i DaguDagRunAttempt
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.IsRoot,
		&i.AttemptID,
		&i.RunCreatedAt,
		&i.AttemptCreatedAt,
		&i.Workspace,
		&i.WorkspaceValid,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DataVersion,
		&i.Data,
		&i.CancelRequested,
		&i.Hidden,
		&i.LocalWorkDir,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRemovableRunsByCount = `-- name: ListRemovableRunsByCount :many
WITH terminal AS (
    SELECT r.dag_run_id, r.run_created_at
    FROM dagu_dag_runs AS r
    WHERE r.is_root
      AND r.dag_name = $1
      AND r.data ? 'status'
      AND r.status <> ALL($2::integer[])
),
ranked AS (
    SELECT r.dag_run_id, r.run_created_at
    FROM dagu_dag_runs AS r
    WHERE r.is_root
      AND r.dag_name = $1
    ORDER BY r.run_created_at DESC, r.dag_run_id ASC
    OFFSET $3::integer
),
removable AS (
    SELECT ranked.dag_run_id, ranked.run_created_at
    FROM ranked
    JOIN terminal USING (dag_run_id)
)
SELECT dag_run_id
FROM removable
ORDER BY run_created_at DESC, dag_run_id ASC
`

type ListRemovableRunsByCountParams struct {
	DagName        string  `json:"dag_name"`
	ActiveStatuses []int32 `json:"active_statuses"`
	RetentionRuns  int32   `json:"retention_runs"`
}

func (q *Queries) ListRemovableRunsByCount(ctx context.Context, arg ListRemovableRunsByCountParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRemovableRunsByCount, arg.DagName, arg.ActiveStatuses, arg.RetentionRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dag_run_id string
		if err := rows.Scan(&dag_run_id); err != nil {
			return nil, err
		}
		items = append(items, dag_run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemovableRunsByDays = `-- name: ListRemovableRunsByDays :many
SELECT dag_run_id
FROM dagu_dag_runs
WHERE is_root
  AND dag_name = $1
  AND run_created_at < $2::timestamptz
  AND updated_at < $2::timestamptz
  AND data ? 'status'
  AND status <> ALL($3::integer[])
ORDER BY run_created_at ASC, dag_run_id ASC
`

type ListRemovableRunsByDaysParams struct {
	DagName        string             `json:"dag_name"`
	Cutoff         pgtype.Timestamptz `json:"cutoff"`
	ActiveStatuses []int32            `json:"active_statuses"`
}

func (q *Queries) ListRemovableRunsByDays(ctx context.Context, arg ListRemovableRunsByDaysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRemovableRunsByDays, arg.DagName, arg.Cutoff, arg.ActiveStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dag_run_id string
		if err := rows.Scan(&dag_run_id); err != nil {
			return nil, err
		}
		items = append(items, dag_run_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootStatusRows = `-- name: ListRootStatusRows :many
SELECT id, dag_name, dag_run_id, root_dag_name, root_dag_run_id, is_root, run_created_at, latest_attempt_id, latest_attempt_created_at, workspace, workspace_valid, status, started_at, finished_at, data_version, data, created_at, updated_at
FROM dagu_dag_runs
WHERE is_root
  AND data ? 'status'
  AND ($1::text = '' OR dag_name::text = $1::text)
  AND ($2::text = '' OR data #>> '{status,name}' ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR dag_run_id::text LIKE '%' || $3::text || '%')
  AND (NOT $4::boolean OR run_created_at >= $5::timestamptz)
  AND (NOT $6::boolean OR run_created_at <= $7::timestamptz)
  AND (cardinality($8::integer[]) = 0 OR status = ANY($8::integer[]))
  AND (
      NOT $9::boolean
      OR (
          workspace_valid
          AND (
              (workspace IS NULL AND $10::boolean)
              OR workspace::text = ANY($11::text[])
          )
      )
  )
  AND (
      NOT $12::boolean
      OR run_created_at < $13::timestamptz
      OR (
          run_created_at = $13::timestamptz
          AND dag_name::text > $14::text
      )
      OR (
          run_created_at = $13::timestamptz
          AND dag_name::text = $14::text
          AND dag_run_id::text > $15::text
      )
  )
ORDER BY run_created_at DESC, dag_name ASC, dag_run_id ASC
LIMIT $16::integer
`

type ListRootStatusRowsParams struct {
	ExactName              string             `json:"exact_name"`
	NameContains           string             `json:"name_contains"`
	DagRunIDContains       string             `json:"dag_run_id_contains"`
	HasFrom                bool               `json:"has_from"`
	FromAt                 pgtype.Timestamptz `json:"from_at"`
	HasTo                  bool               `json:"has_to"`
	ToAt                   pgtype.Timestamptz `json:"to_at"`
	Statuses               []int32            `json:"statuses"`
	WorkspaceFilterEnabled bool               `json:"workspace_filter_enabled"`
	IncludeUnlabelled      bool               `json:"include_unlabelled"`
	Workspaces             []string           `json:"workspaces"`
	CursorSet              bool               `json:"cursor_set"`
	CursorTimestamp        pgtype.Timestamptz `json:"cursor_timestamp"`
	CursorName             string             `json:"cursor_name"`
	CursorDagRunID         string             `json:"cursor_dag_run_id"`
	PageLimit              int32              `json:"page_limit"`
}

func (q *Queries) ListRootStatusRows(ctx context.Context, arg ListRootStatusRowsParams) ([]DaguDagRun, error) {
	rows, err := q.db.Query(ctx, listRootStatusRows,
		arg.ExactName,
		arg.NameContains,
		arg.DagRunIDContains,
		arg.HasFrom,
		arg.FromAt,
		arg.HasTo,
		arg.ToAt,
		arg.Statuses,
		arg.WorkspaceFilterEnabled,
		arg.IncludeUnlabelled,
		arg.Workspaces,
		arg.CursorSet,
		arg.CursorTimestamp,
		arg.CursorName,
		arg.CursorDagRunID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguDagRun{}
	for rows.Next() {
		var i DaguDagRun
		if err := rows.Scan(
			&i.ID,
			&i.DagName,
			&i.DagRunID,
			&i.RootDagName,
			&i.RootDagRunID,
			&i.IsRoot,
			&i.RunCreatedAt,
			&i.LatestAttemptID,
			&i.LatestAttemptCreatedAt,
			&i.Workspace,
			&i.WorkspaceValid,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDAGRunKey = `-- name: LockDAGRunKey :exec
SELECT pg_advisory_xact_lock(
    hashtext($1::text),
    hashtext('dagu-dag-run:' || $1::text)
)
`

func (q *Queries) LockDAGRunKey(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockDAGRunKey, lockKey)
	return err
}

const mergeAttemptStepMessages = `-- name: MergeAttemptStepMessages :exec
UPDATE dagu_dag_run_attempts
SET data = jsonb_set(
        jsonb_set(data, '{messages}', coalesce(data -> 'messages', '{}'::jsonb), true),
        ARRAY['messages', $1::text],
        $2::jsonb,
        true
    ),
    updated_at = now()
WHERE id = $3
`

type MergeAttemptStepMessagesParams struct {
	StepName         string    `json:"step_name"`
	StepMessagesJson []byte    `json:"step_messages_json"`
	ID               uuid.UUID `json:"id"`
}

func (q *Queries) MergeAttemptStepMessages(ctx context.Context, arg MergeAttemptStepMessagesParams) error {
	_, err := q.db.Exec(ctx, mergeAttemptStepMessages, arg.StepName, arg.StepMessagesJson, arg.ID)
	return err
}

const recentAttemptsByName = `-- name: RecentAttemptsByName :many
SELECT a.id, a.run_id, a.dag_name, a.dag_run_id, a.root_dag_name, a.root_dag_run_id, a.is_root, a.attempt_id, a.run_created_at, a.attempt_created_at, a.workspace, a.workspace_valid, a.status, a.started_at, a.finished_at, a.data_version, a.data, a.cancel_requested, a.hidden, a.local_work_dir, a.created_at, a.updated_at
FROM dagu_dag_runs r
JOIN dagu_dag_run_attempts a ON a.id = r.latest_attempt_id
WHERE r.is_root
  AND r.dag_name = $1
  AND r.data ? 'status'
  AND NOT a.hidden
ORDER BY r.run_created_at DESC, r.dag_run_id ASC
LIMIT $2::integer
`

type RecentAttemptsByNameParams struct {
	DagName   string `json:"dag_name"`
	ItemLimit int32  `json:"item_limit"`
}

func (q *Queries) RecentAttemptsByName(ctx context.Context, arg RecentAttemptsByNameParams) ([]DaguDagRunAttempt, error) {
	rows, err := q.db.Query(ctx, recentAttemptsByName, arg.DagName, arg.ItemLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguDagRunAttempt{}
	for rows.Next() {
		var i DaguDagRunAttempt
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.DagName,
			&i.DagRunID,
			&i.RootDagName,
			&i.RootDagRunID,
			&i.IsRoot,
			&i.AttemptID,
			&i.RunCreatedAt,
			&i.AttemptCreatedAt,
			&i.Workspace,
			&i.WorkspaceValid,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DataVersion,
			&i.Data,
			&i.CancelRequested,
			&i.Hidden,
			&i.LocalWorkDir,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameDAGRuns = `-- name: RenameDAGRuns :exec
WITH renamed_runs AS (
    UPDATE dagu_dag_runs
    SET dag_name = CASE WHEN is_root AND dag_name::text = $1::text THEN $2 ELSE dag_name END,
        root_dag_name = CASE WHEN root_dag_name::text = $1::text THEN $2 ELSE root_dag_name END,
        data = CASE
            WHEN is_root
             AND dag_name::text = $1::text
             AND data ? 'status'
            THEN jsonb_set(data, '{status,name}', to_jsonb($2::text), true)
            ELSE data
        END,
        updated_at = now()
    WHERE root_dag_name::text = $1::text
       OR (is_root AND dag_name::text = $1::text)
    RETURNING id
)
UPDATE dagu_dag_run_attempts
SET dag_name = CASE WHEN is_root AND dag_name::text = $1::text THEN $2 ELSE dag_name END,
    root_dag_name = CASE WHEN root_dag_name::text = $1::text THEN $2 ELSE root_dag_name END,
    data = CASE
        WHEN is_root
         AND dag_name::text = $1::text
         AND data ? 'status'
        THEN jsonb_set(data, '{status,name}', to_jsonb($2::text), true)
        ELSE data
    END,
    updated_at = now()
WHERE run_id IN (SELECT id FROM renamed_runs)
`

type RenameDAGRunsParams struct {
	OldName string `json:"old_name"`
	NewName string `json:"new_name"`
}

func (q *Queries) RenameDAGRuns(ctx context.Context, arg RenameDAGRunsParams) error {
	_, err := q.db.Exec(ctx, renameDAGRuns, arg.OldName, arg.NewName)
	return err
}

const setAttemptCancelRequested = `-- name: SetAttemptCancelRequested :exec
UPDATE dagu_dag_run_attempts
SET cancel_requested = true,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) SetAttemptCancelRequested(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAttemptCancelRequested, id)
	return err
}

const setAttemptHidden = `-- name: SetAttemptHidden :exec
WITH hidden_attempt AS (
    UPDATE dagu_dag_run_attempts AS a
    SET hidden = true,
        updated_at = now()
    WHERE a.id = $1
    RETURNING a.id, a.run_id
),
latest AS (
    SELECT a.id, a.run_id, a.dag_name, a.dag_run_id, a.root_dag_name, a.root_dag_run_id, a.is_root, a.attempt_id, a.run_created_at, a.attempt_created_at, a.workspace, a.workspace_valid, a.status, a.started_at, a.finished_at, a.data_version, a.data, a.cancel_requested, a.hidden, a.local_work_dir, a.created_at, a.updated_at
    FROM dagu_dag_run_attempts a
    JOIN hidden_attempt h ON a.run_id = h.run_id
    WHERE a.id <> h.id
      AND NOT a.hidden
      AND a.data ? 'status'
    ORDER BY a.attempt_created_at DESC, a.id DESC
    LIMIT 1
),
summary_updated AS (
    UPDATE dagu_dag_runs r
    SET latest_attempt_id = l.id,
        latest_attempt_created_at = l.attempt_created_at,
        workspace = l.workspace,
        workspace_valid = l.workspace_valid,
        status = l.status,
        started_at = l.started_at,
        finished_at = l.finished_at,
        data = jsonb_build_object('status', l.data -> 'status'),
        updated_at = now()
    FROM latest l
    WHERE r.id = l.run_id
    RETURNING r.id
)
UPDATE dagu_dag_runs r
SET latest_attempt_id = NULL,
    latest_attempt_created_at = NULL,
    workspace = NULL,
    workspace_valid = true,
    status = NULL,
    started_at = NULL,
    finished_at = NULL,
    data = '{}'::jsonb,
    updated_at = now()
WHERE r.id IN (SELECT run_id FROM hidden_attempt)
  AND NOT EXISTS (SELECT 1 FROM summary_updated)
`

func (q *Queries) SetAttemptHidden(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAttemptHidden, id)
	return err
}

const updateAttemptDAG = `-- name: UpdateAttemptDAG :exec
UPDATE dagu_dag_run_attempts
SET data = jsonb_set(data, '{dag}', $1::jsonb, true),
    updated_at = now()
WHERE id = $2
`

type UpdateAttemptDAGParams struct {
	DagJson []byte    `json:"dag_json"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAttemptDAG(ctx context.Context, arg UpdateAttemptDAGParams) error {
	_, err := q.db.Exec(ctx, updateAttemptDAG, arg.DagJson, arg.ID)
	return err
}

const updateAttemptMessages = `-- name: UpdateAttemptMessages :exec
UPDATE dagu_dag_run_attempts
SET data = jsonb_set(data, '{messages}', $1::jsonb, true),
    updated_at = now()
WHERE id = $2
`

type UpdateAttemptMessagesParams struct {
	MessagesJson []byte    `json:"messages_json"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAttemptMessages(ctx context.Context, arg UpdateAttemptMessagesParams) error {
	_, err := q.db.Exec(ctx, updateAttemptMessages, arg.MessagesJson, arg.ID)
	return err
}

const updateAttemptOutputs = `-- name: UpdateAttemptOutputs :exec
UPDATE dagu_dag_run_attempts
SET data = CASE
        WHEN $1::jsonb IS NULL THEN data - 'outputs'
        ELSE jsonb_set(data, '{outputs}', $1::jsonb, true)
    END,
    updated_at = now()
WHERE id = $2
`

type UpdateAttemptOutputsParams struct {
	OutputsJson []byte    `json:"outputs_json"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAttemptOutputs(ctx context.Context, arg UpdateAttemptOutputsParams) error {
	_, err := q.db.Exec(ctx, updateAttemptOutputs, arg.OutputsJson, arg.ID)
	return err
}

const updateAttemptStatus = `-- name: UpdateAttemptStatus :exec
WITH updated_attempt AS (
    UPDATE dagu_dag_run_attempts AS a
    SET data = jsonb_set(data, '{status}', $1::jsonb, true),
        status = $2::dagu_status_code,
        workspace = $3,
        workspace_valid = $4,
        started_at = $5,
        finished_at = $6,
        updated_at = now()
    WHERE a.id = $7
    RETURNING a.id, a.run_id, a.attempt_created_at, a.workspace, a.workspace_valid, a.status, a.started_at, a.finished_at, a.data, a.hidden
)
UPDATE dagu_dag_runs r
SET latest_attempt_id = ua.id,
    latest_attempt_created_at = ua.attempt_created_at,
    workspace = ua.workspace,
    workspace_valid = ua.workspace_valid,
    status = ua.status,
    started_at = ua.started_at,
    finished_at = ua.finished_at,
    data = jsonb_build_object('status', ua.data -> 'status'),
    updated_at = now()
FROM updated_attempt ua
WHERE r.id = ua.run_id
  AND NOT ua.hidden
  AND (
      r.latest_attempt_id IS NULL
      OR r.latest_attempt_created_at IS NULL
      OR ua.attempt_created_at > r.latest_attempt_created_at
      OR (ua.attempt_created_at = r.latest_attempt_created_at AND ua.id >= r.latest_attempt_id)
  )
`

type UpdateAttemptStatusParams struct {
	StatusJson     []byte             `json:"status_json"`
	Status         int32              `json:"status"`
	Workspace      sql.NullString     `json:"workspace"`
	WorkspaceValid bool               `json:"workspace_valid"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateAttemptStatus(ctx context.Context, arg UpdateAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updateAttemptStatus,
		arg.StatusJson,
		arg.Status,
		arg.Workspace,
		arg.WorkspaceValid,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
