// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :exec
INSERT INTO dagu_audit_entries (
    id,
    occurred_at,
    category,
    action,
    user_id,
    username,
    ip_address,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NULLIF($7, ''),
    $8
)
`

type AppendAuditEntryParams struct {
	ID         uuid.UUID          `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Category   string             `json:"category"`
	Action     string             `json:"action"`
	UserID     string             `json:"user_id"`
	Username   string             `json:"username"`
	IpAddress  interface{}        `json:"ip_address"`
	Data       []byte             `json:"data"`
}

func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) error {
	_, err := q.db.Exec(ctx, appendAuditEntry,
		arg.ID,
		arg.OccurredAt,
		arg.Category,
		arg.Action,
		arg.UserID,
		arg.Username,
		arg.IpAddress,
		arg.Data,
	)
	return err
}

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT count(*)::integer
FROM dagu_audit_entries
WHERE (NOT $1::boolean OR category = $2)
  AND (NOT $3::boolean OR user_id = $4)
  AND (NOT $5::boolean OR occurred_at >= $6)
  AND (NOT $7::boolean OR occurred_at < $8)
`

type CountAuditEntriesParams struct {
	HasCategory  bool               `json:"has_category"`
	Category     string             `json:"category"`
	HasUserID    bool               `json:"has_user_id"`
	UserID       string             `json:"user_id"`
	HasStartTime bool               `json:"has_start_time"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	HasEndTime   bool               `json:"has_end_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CountAuditEntries(ctx context.Context, arg CountAuditEntriesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAuditEntries,
		arg.HasCategory,
		arg.Category,
		arg.HasUserID,
		arg.UserID,
		arg.HasStartTime,
		arg.StartTime,
		arg.HasEndTime,
		arg.EndTime,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const queryAuditEntries = `-- name: QueryAuditEntries :many
SELECT id, occurred_at, category, action, user_id, username, ip_address, data_version, data, created_at
FROM dagu_audit_entries
WHERE (NOT $1::boolean OR category = $2)
  AND (NOT $3::boolean OR user_id = $4)
  AND (NOT $5::boolean OR occurred_at >= $6)
  AND (NOT $7::boolean OR occurred_at < $8)
ORDER BY occurred_at DESC, id DESC
LIMIT $10::integer
OFFSET $9::integer
`

type QueryAuditEntriesParams struct {
	HasCategory  bool               `json:"has_category"`
	Category     string             `json:"category"`
	HasUserID    bool               `json:"has_user_id"`
	UserID       string             `json:"user_id"`
	HasStartTime bool               `json:"has_start_time"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	HasEndTime   bool               `json:"has_end_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	RowOffset    int32              `json:"row_offset"`
	RowLimit     int32              `json:"row_limit"`
}

func (q *Queries) QueryAuditEntries(ctx context.Context, arg QueryAuditEntriesParams) ([]DaguAuditEntry, error) {
	rows, err := q.db.Query(ctx, queryAuditEntries,
		arg.HasCategory,
		arg.Category,
		arg.HasUserID,
		arg.UserID,
		arg.HasStartTime,
		arg.StartTime,
		arg.HasEndTime,
		arg.EndTime,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguAuditEntry{}
	for rows.Next() {
		var i DaguAuditEntry
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Category,
			&i.Action,
			&i.UserID,
			&i.Username,
			&i.IpAddress,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
