// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint
FROM dagu_users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO dagu_api_keys (
    id,
    name,
    role,
    key_hash,
    key_prefix,
    created_by,
    workspace_access,
    last_used_at,
    data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateAPIKeyParams struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	KeyHash         string             `json:"key_hash"`
	KeyPrefix       string             `json:"key_prefix"`
	CreatedBy       string             `json:"created_by"`
	WorkspaceAccess []byte             `json:"workspace_access"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.CreatedBy,
		arg.WorkspaceAccess,
		arg.LastUsedAt,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO dagu_users (
    id,
    username,
    password_hash,
    role,
    auth_provider,
    oidc_issuer,
    oidc_subject,
    is_disabled,
    workspace_access,
    data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5, ''),
    NULLIF($6, ''),
    NULLIF($7, ''),
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type CreateUserParams struct {
	ID              uuid.UUID          `json:"id"`
	Username        string             `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	AuthProvider    interface{}        `json:"auth_provider"`
	OidcIssuer      interface{}        `json:"oidc_issuer"`
	OidcSubject     interface{}        `json:"oidc_subject"`
	IsDisabled      bool               `json:"is_disabled"`
	WorkspaceAccess []byte             `json:"workspace_access"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.AuthProvider,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.IsDisabled,
		arg.WorkspaceAccess,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWebhook = `-- name: CreateWebhook :exec
INSERT INTO dagu_webhooks (
    id,
    dag_name,
    token_hash,
    token_prefix,
    enabled,
    auth_mode,
    hmac_enforcement_mode,
    created_by,
    last_used_at,
    data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NULLIF($6, ''),
    NULLIF($7, ''),
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type CreateWebhookParams struct {
	ID                  uuid.UUID          `json:"id"`
	DagName             string             `json:"dag_name"`
	TokenHash           string             `json:"token_hash"`
	TokenPrefix         string             `json:"token_prefix"`
	Enabled             bool               `json:"enabled"`
	AuthMode            interface{}        `json:"auth_mode"`
	HmacEnforcementMode interface{}        `json:"hmac_enforcement_mode"`
	CreatedBy           string             `json:"created_by"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	Data                []byte             `json:"data"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) error {
	_, err := q.db.Exec(ctx, createWebhook,
		arg.ID,
		arg.DagName,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Enabled,
		arg.AuthMode,
		arg.HmacEnforcementMode,
		arg.CreatedBy,
		arg.LastUsedAt,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM dagu_api_keys
WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM dagu_users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM dagu_webhooks
WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhookByDAGName = `-- name: DeleteWebhookByDAGName :execrows
DELETE FROM dagu_webhooks
WHERE dag_name = $1
`

func (q *Queries) DeleteWebhookByDAGName(ctx context.Context, dagName string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookByDAGName, dagName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, role, key_hash, key_prefix, created_by, workspace_access, last_used_at, data_version, data, created_at, updated_at
FROM dagu_api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (DaguApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i DaguApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedBy,
		&i.WorkspaceAccess,
		&i.LastUsedAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, auth_provider, oidc_issuer, oidc_subject, is_disabled, workspace_access, data_version, data, created_at, updated_at
FROM dagu_users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (DaguUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i DaguUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.AuthProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.IsDisabled,
		&i.WorkspaceAccess,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOIDCIdentity = `-- name: GetUserByOIDCIdentity :one
SELECT id, username, password_hash, role, auth_provider, oidc_issuer, oidc_subject, is_disabled, workspace_access, data_version, data, created_at, updated_at
FROM dagu_users
WHERE oidc_issuer = $1
  AND oidc_subject = $2
`

type GetUserByOIDCIdentityParams struct {
	OidcIssuer  pgtype.Text `json:"oidc_issuer"`
	OidcSubject pgtype.Text `json:"oidc_subject"`
}

func (q *Queries) GetUserByOIDCIdentity(ctx context.Context, arg GetUserByOIDCIdentityParams) (DaguUser, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCIdentity, arg.OidcIssuer, arg.OidcSubject)
	var i DaguUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.AuthProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.IsDisabled,
		&i.WorkspaceAccess,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, auth_provider, oidc_issuer, oidc_subject, is_disabled, workspace_access, data_version, data, created_at, updated_at
FROM dagu_users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (DaguUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i DaguUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.AuthProvider,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.IsDisabled,
		&i.WorkspaceAccess,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByDAGName = `-- name: GetWebhookByDAGName :one
SELECT id, dag_name, token_hash, token_prefix, enabled, auth_mode, hmac_enforcement_mode, created_by, last_used_at, data_version, data, created_at, updated_at
FROM dagu_webhooks
WHERE dag_name = $1
`

func (q *Queries) GetWebhookByDAGName(ctx context.Context, dagName string) (DaguWebhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByDAGName, dagName)
	var i DaguWebhook
	err := row.Scan(
		&i.ID,
		&i.DagName,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Enabled,
		&i.AuthMode,
		&i.HmacEnforcementMode,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, dag_name, token_hash, token_prefix, enabled, auth_mode, hmac_enforcement_mode, created_by, last_used_at, data_version, data, created_at, updated_at
FROM dagu_webhooks
WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id uuid.UUID) (DaguWebhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i DaguWebhook
	err := row.Scan(
		&i.ID,
		&i.DagName,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Enabled,
		&i.AuthMode,
		&i.HmacEnforcementMode,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, role, key_hash, key_prefix, created_by, workspace_access, last_used_at, data_version, data, created_at, updated_at
FROM dagu_api_keys
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]DaguApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguApiKey{}
	for rows.Next() {
		var i DaguApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedBy,
			&i.WorkspaceAccess,
			&i.LastUsedAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, auth_provider, oidc_issuer, oidc_subject, is_disabled, workspace_access, data_version, data, created_at, updated_at
FROM dagu_users
ORDER BY username ASC, id ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]DaguUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguUser{}
	for rows.Next() {
		var i DaguUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.AuthProvider,
			&i.OidcIssuer,
			&i.OidcSubject,
			&i.IsDisabled,
			&i.WorkspaceAccess,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, dag_name, token_hash, token_prefix, enabled, auth_mode, hmac_enforcement_mode, created_by, last_used_at, data_version, data, created_at, updated_at
FROM dagu_webhooks
ORDER BY dag_name ASC, id ASC
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]DaguWebhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguWebhook{}
	for rows.Next() {
		var i DaguWebhook
		if err := rows.Scan(
			&i.ID,
			&i.DagName,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Enabled,
			&i.AuthMode,
			&i.HmacEnforcementMode,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKey = `-- name: UpdateAPIKey :execrows
UPDATE dagu_api_keys
SET name = $1,
    role = $2,
    key_hash = $3,
    key_prefix = $4,
    created_by = $5,
    workspace_access = $6,
    last_used_at = $7,
    data = $8,
    updated_at = $9
WHERE id = $10
`

type UpdateAPIKeyParams struct {
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	KeyHash         string             `json:"key_hash"`
	KeyPrefix       string             `json:"key_prefix"`
	CreatedBy       string             `json:"created_by"`
	WorkspaceAccess []byte             `json:"workspace_access"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	Data            []byte             `json:"data"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAPIKey,
		arg.Name,
		arg.Role,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.CreatedBy,
		arg.WorkspaceAccess,
		arg.LastUsedAt,
		arg.Data,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :execrows
UPDATE dagu_api_keys
SET last_used_at = $1,
    data = jsonb_set(data, '{last_used_at}', to_jsonb($1::timestamptz), true),
    updated_at = now()
WHERE id = $2
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE dagu_users
SET username = $1,
    password_hash = $2,
    role = $3,
    auth_provider = NULLIF($4, ''),
    oidc_issuer = NULLIF($5, ''),
    oidc_subject = NULLIF($6, ''),
    is_disabled = $7,
    workspace_access = $8,
    data = $9,
    updated_at = $10
WHERE id = $11
`

type UpdateUserParams struct {
	Username        string             `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	AuthProvider    interface{}        `json:"auth_provider"`
	OidcIssuer      interface{}        `json:"oidc_issuer"`
	OidcSubject     interface{}        `json:"oidc_subject"`
	IsDisabled      bool               `json:"is_disabled"`
	WorkspaceAccess []byte             `json:"workspace_access"`
	Data            []byte             `json:"data"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.AuthProvider,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.IsDisabled,
		arg.WorkspaceAccess,
		arg.Data,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhook = `-- name: UpdateWebhook :execrows
UPDATE dagu_webhooks
SET dag_name = $1,
    token_hash = $2,
    token_prefix = $3,
    enabled = $4,
    auth_mode = NULLIF($5, ''),
    hmac_enforcement_mode = NULLIF($6, ''),
    created_by = $7,
    last_used_at = $8,
    data = $9,
    updated_at = $10
WHERE id = $11
`

type UpdateWebhookParams struct {
	DagName             string             `json:"dag_name"`
	TokenHash           string             `json:"token_hash"`
	TokenPrefix         string             `json:"token_prefix"`
	Enabled             bool               `json:"enabled"`
	AuthMode            interface{}        `json:"auth_mode"`
	HmacEnforcementMode interface{}        `json:"hmac_enforcement_mode"`
	CreatedBy           string             `json:"created_by"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	Data                []byte             `json:"data"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ID                  uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebhook,
		arg.DagName,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Enabled,
		arg.AuthMode,
		arg.HmacEnforcementMode,
		arg.CreatedBy,
		arg.LastUsedAt,
		arg.Data,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhookLastUsed = `-- name: UpdateWebhookLastUsed :execrows
UPDATE dagu_webhooks
SET last_used_at = $1,
    data = jsonb_set(data, '{lastUsedAt}', to_jsonb($1::timestamptz), true),
    updated_at = now()
WHERE id = $2
`

type UpdateWebhookLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateWebhookLastUsed(ctx context.Context, arg UpdateWebhookLastUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebhookLastUsed, arg.LastUsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
