// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: distributed.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDispatchTaskByID = `-- name: ClaimDispatchTaskByID :one
UPDATE dagu_dispatch_tasks
SET claim_token = $1,
    claimed_at = $2,
    claim_expires_at = $3,
    worker_id = $4,
    poller_id = $5,
    owner_id = NULLIF($6, ''),
    owner_host = NULLIF($7, ''),
    owner_port = $8,
    data = $9,
    updated_at = now()
WHERE id = $10
RETURNING id, queue_name, attempt_key, worker_selector, data_version, data, enqueued_at, claim_token, claimed_at, claim_expires_at, worker_id, poller_id, owner_id, owner_host, owner_port, created_at, updated_at
`

type ClaimDispatchTaskByIDParams struct {
	ClaimToken     uuid.NullUUID      `json:"claim_token"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ClaimExpiresAt pgtype.Timestamptz `json:"claim_expires_at"`
	WorkerID       pgtype.Text        `json:"worker_id"`
	PollerID       pgtype.Text        `json:"poller_id"`
	OwnerID        interface{}        `json:"owner_id"`
	OwnerHost      interface{}        `json:"owner_host"`
	OwnerPort      pgtype.Int4        `json:"owner_port"`
	Data           []byte             `json:"data"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) ClaimDispatchTaskByID(ctx context.Context, arg ClaimDispatchTaskByIDParams) (DaguDispatchTask, error) {
	row := q.db.QueryRow(ctx, claimDispatchTaskByID,
		arg.ClaimToken,
		arg.ClaimedAt,
		arg.ClaimExpiresAt,
		arg.WorkerID,
		arg.PollerID,
		arg.OwnerID,
		arg.OwnerHost,
		arg.OwnerPort,
		arg.Data,
		arg.ID,
	)
	var i DaguDispatchTask
	err := row.Scan(
		&i.ID,
		&i.QueueName,
		&i.AttemptKey,
		&i.WorkerSelector,
		&i.DataVersion,
		&i.Data,
		&i.EnqueuedAt,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.WorkerID,
		&i.PollerID,
		&i.OwnerID,
		&i.OwnerHost,
		&i.OwnerPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOutstandingDispatchTasksByQueue = `-- name: CountOutstandingDispatchTasksByQueue :one
SELECT count(*)::integer
FROM dagu_dispatch_tasks
WHERE ($1::text = '' OR queue_name = $1::text)
  AND (claim_token IS NULL OR claim_expires_at > now())
`

func (q *Queries) CountOutstandingDispatchTasksByQueue(ctx context.Context, queueName string) (int32, error) {
	row := q.db.QueryRow(ctx, countOutstandingDispatchTasksByQueue, queueName)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteActiveDistributedRun = `-- name: DeleteActiveDistributedRun :execrows
DELETE FROM dagu_active_distributed_runs
WHERE attempt_key = $1
`

func (q *Queries) DeleteActiveDistributedRun(ctx context.Context, attemptKey string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActiveDistributedRun, attemptKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDAGRunLease = `-- name: DeleteDAGRunLease :execrows
DELETE FROM dagu_dag_run_leases
WHERE attempt_key = $1
`

func (q *Queries) DeleteDAGRunLease(ctx context.Context, attemptKey string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDAGRunLease, attemptKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDispatchTaskClaim = `-- name: DeleteDispatchTaskClaim :execrows
DELETE FROM dagu_dispatch_tasks
WHERE claim_token = $1
`

func (q *Queries) DeleteDispatchTaskClaim(ctx context.Context, claimToken uuid.NullUUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDispatchTaskClaim, claimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredPendingDispatchTasks = `-- name: DeleteExpiredPendingDispatchTasks :execrows
DELETE FROM dagu_dispatch_tasks
WHERE claim_token IS NULL
  AND enqueued_at <= now() - $1::bigint * interval '1 second'
`

func (q *Queries) DeleteExpiredPendingDispatchTasks(ctx context.Context, staleSeconds int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPendingDispatchTasks, staleSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleWorkerHeartbeats = `-- name: DeleteStaleWorkerHeartbeats :execrows
DELETE FROM dagu_worker_heartbeats
WHERE last_heartbeat_at < $1
`

func (q *Queries) DeleteStaleWorkerHeartbeats(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleWorkerHeartbeats, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueDispatchTask = `-- name: EnqueueDispatchTask :exec
INSERT INTO dagu_dispatch_tasks (
    id,
    queue_name,
    attempt_key,
    worker_selector,
    data,
    enqueued_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type EnqueueDispatchTaskParams struct {
	ID             uuid.UUID          `json:"id"`
	QueueName      string             `json:"queue_name"`
	AttemptKey     string             `json:"attempt_key"`
	WorkerSelector []byte             `json:"worker_selector"`
	Data           []byte             `json:"data"`
	EnqueuedAt     pgtype.Timestamptz `json:"enqueued_at"`
}

func (q *Queries) EnqueueDispatchTask(ctx context.Context, arg EnqueueDispatchTaskParams) error {
	_, err := q.db.Exec(ctx, enqueueDispatchTask,
		arg.ID,
		arg.QueueName,
		arg.AttemptKey,
		arg.WorkerSelector,
		arg.Data,
		arg.EnqueuedAt,
	)
	return err
}

const findClaimableDispatchTask = `-- name: FindClaimableDispatchTask :one
SELECT id, queue_name, attempt_key, worker_selector, data_version, data, enqueued_at, claim_token, claimed_at, claim_expires_at, worker_id, poller_id, owner_id, owner_host, owner_port, created_at, updated_at
FROM dagu_dispatch_tasks
WHERE (claim_token IS NULL OR claim_expires_at <= now())
  AND worker_selector <@ $1::jsonb
ORDER BY enqueued_at ASC, id ASC
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) FindClaimableDispatchTask(ctx context.Context, workerLabels []byte) (DaguDispatchTask, error) {
	row := q.db.QueryRow(ctx, findClaimableDispatchTask, workerLabels)
	var i DaguDispatchTask
	err := row.Scan(
		&i.ID,
		&i.QueueName,
		&i.AttemptKey,
		&i.WorkerSelector,
		&i.DataVersion,
		&i.Data,
		&i.EnqueuedAt,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.WorkerID,
		&i.PollerID,
		&i.OwnerID,
		&i.OwnerHost,
		&i.OwnerPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveDistributedRun = `-- name: GetActiveDistributedRun :one
SELECT attempt_key, dag_name, dag_run_id, root_dag_name, root_dag_run_id, attempt_id, worker_id, status, observed_at, data_version, data, created_at, updated_at
FROM dagu_active_distributed_runs
WHERE attempt_key = $1
`

func (q *Queries) GetActiveDistributedRun(ctx context.Context, attemptKey string) (DaguActiveDistributedRun, error) {
	row := q.db.QueryRow(ctx, getActiveDistributedRun, attemptKey)
	var i DaguActiveDistributedRun
	err := row.Scan(
		&i.AttemptKey,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.AttemptID,
		&i.WorkerID,
		&i.Status,
		&i.ObservedAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDAGRunLease = `-- name: GetDAGRunLease :one
SELECT attempt_key, dag_name, dag_run_id, root_dag_name, root_dag_run_id, attempt_id, queue_name, worker_id, owner_id, owner_host, owner_port, claimed_at, last_heartbeat_at, data_version, data, created_at, updated_at
FROM dagu_dag_run_leases
WHERE attempt_key = $1
`

func (q *Queries) GetDAGRunLease(ctx context.Context, attemptKey string) (DaguDagRunLease, error) {
	row := q.db.QueryRow(ctx, getDAGRunLease, attemptKey)
	var i DaguDagRunLease
	err := row.Scan(
		&i.AttemptKey,
		&i.DagName,
		&i.DagRunID,
		&i.RootDagName,
		&i.RootDagRunID,
		&i.AttemptID,
		&i.QueueName,
		&i.WorkerID,
		&i.OwnerID,
		&i.OwnerHost,
		&i.OwnerPort,
		&i.ClaimedAt,
		&i.LastHeartbeatAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDispatchTaskClaim = `-- name: GetDispatchTaskClaim :one
SELECT id, queue_name, attempt_key, worker_selector, data_version, data, enqueued_at, claim_token, claimed_at, claim_expires_at, worker_id, poller_id, owner_id, owner_host, owner_port, created_at, updated_at
FROM dagu_dispatch_tasks
WHERE claim_token = $1
`

func (q *Queries) GetDispatchTaskClaim(ctx context.Context, claimToken uuid.NullUUID) (DaguDispatchTask, error) {
	row := q.db.QueryRow(ctx, getDispatchTaskClaim, claimToken)
	var i DaguDispatchTask
	err := row.Scan(
		&i.ID,
		&i.QueueName,
		&i.AttemptKey,
		&i.WorkerSelector,
		&i.DataVersion,
		&i.Data,
		&i.EnqueuedAt,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.ClaimExpiresAt,
		&i.WorkerID,
		&i.PollerID,
		&i.OwnerID,
		&i.OwnerHost,
		&i.OwnerPort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerHeartbeat = `-- name: GetWorkerHeartbeat :one
SELECT worker_id, labels, stats, last_heartbeat_at, data_version, data, created_at, updated_at
FROM dagu_worker_heartbeats
WHERE worker_id = $1
`

func (q *Queries) GetWorkerHeartbeat(ctx context.Context, workerID string) (DaguWorkerHeartbeat, error) {
	row := q.db.QueryRow(ctx, getWorkerHeartbeat, workerID)
	var i DaguWorkerHeartbeat
	err := row.Scan(
		&i.WorkerID,
		&i.Labels,
		&i.Stats,
		&i.LastHeartbeatAt,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasOutstandingDispatchTaskAttempt = `-- name: HasOutstandingDispatchTaskAttempt :one
SELECT EXISTS (
    SELECT 1
    FROM dagu_dispatch_tasks
    WHERE attempt_key = $1
      AND (claim_token IS NULL OR claim_expires_at > now())
)
`

func (q *Queries) HasOutstandingDispatchTaskAttempt(ctx context.Context, attemptKey string) (bool, error) {
	row := q.db.QueryRow(ctx, hasOutstandingDispatchTaskAttempt, attemptKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveDistributedRuns = `-- name: ListActiveDistributedRuns :many
SELECT attempt_key, dag_name, dag_run_id, root_dag_name, root_dag_run_id, attempt_id, worker_id, status, observed_at, data_version, data, created_at, updated_at
FROM dagu_active_distributed_runs
ORDER BY observed_at DESC, attempt_key ASC
`

func (q *Queries) ListActiveDistributedRuns(ctx context.Context) ([]DaguActiveDistributedRun, error) {
	rows, err := q.db.Query(ctx, listActiveDistributedRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguActiveDistributedRun{}
	for rows.Next() {
		var i DaguActiveDistributedRun
		if err := rows.Scan(
			&i.AttemptKey,
			&i.DagName,
			&i.DagRunID,
			&i.RootDagName,
			&i.RootDagRunID,
			&i.AttemptID,
			&i.WorkerID,
			&i.Status,
			&i.ObservedAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDAGRunLeases = `-- name: ListAllDAGRunLeases :many
SELECT attempt_key, dag_name, dag_run_id, root_dag_name, root_dag_run_id, attempt_id, queue_name, worker_id, owner_id, owner_host, owner_port, claimed_at, last_heartbeat_at, data_version, data, created_at, updated_at
FROM dagu_dag_run_leases
ORDER BY last_heartbeat_at DESC, attempt_key ASC
`

func (q *Queries) ListAllDAGRunLeases(ctx context.Context) ([]DaguDagRunLease, error) {
	rows, err := q.db.Query(ctx, listAllDAGRunLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguDagRunLease{}
	for rows.Next() {
		var i DaguDagRunLease
		if err := rows.Scan(
			&i.AttemptKey,
			&i.DagName,
			&i.DagRunID,
			&i.RootDagName,
			&i.RootDagRunID,
			&i.AttemptID,
			&i.QueueName,
			&i.WorkerID,
			&i.OwnerID,
			&i.OwnerHost,
			&i.OwnerPort,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDAGRunLeasesByQueue = `-- name: ListDAGRunLeasesByQueue :many
SELECT attempt_key, dag_name, dag_run_id, root_dag_name, root_dag_run_id, attempt_id, queue_name, worker_id, owner_id, owner_host, owner_port, claimed_at, last_heartbeat_at, data_version, data, created_at, updated_at
FROM dagu_dag_run_leases
WHERE queue_name = $1
ORDER BY last_heartbeat_at DESC, attempt_key ASC
`

func (q *Queries) ListDAGRunLeasesByQueue(ctx context.Context, queueName string) ([]DaguDagRunLease, error) {
	rows, err := q.db.Query(ctx, listDAGRunLeasesByQueue, queueName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguDagRunLease{}
	for rows.Next() {
		var i DaguDagRunLease
		if err := rows.Scan(
			&i.AttemptKey,
			&i.DagName,
			&i.DagRunID,
			&i.RootDagName,
			&i.RootDagRunID,
			&i.AttemptID,
			&i.QueueName,
			&i.WorkerID,
			&i.OwnerID,
			&i.OwnerHost,
			&i.OwnerPort,
			&i.ClaimedAt,
			&i.LastHeartbeatAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerHeartbeats = `-- name: ListWorkerHeartbeats :many
SELECT worker_id, labels, stats, last_heartbeat_at, data_version, data, created_at, updated_at
FROM dagu_worker_heartbeats
ORDER BY worker_id ASC
`

func (q *Queries) ListWorkerHeartbeats(ctx context.Context) ([]DaguWorkerHeartbeat, error) {
	rows, err := q.db.Query(ctx, listWorkerHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguWorkerHeartbeat{}
	for rows.Next() {
		var i DaguWorkerHeartbeat
		if err := rows.Scan(
			&i.WorkerID,
			&i.Labels,
			&i.Stats,
			&i.LastHeartbeatAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDAGRunLease = `-- name: TouchDAGRunLease :execrows
UPDATE dagu_dag_run_leases
SET last_heartbeat_at = $1,
    data = jsonb_set(data, '{lastHeartbeatAt}', to_jsonb($2::bigint), true),
    updated_at = now()
WHERE attempt_key = $3
`

type TouchDAGRunLeaseParams struct {
	LastHeartbeatAt       pgtype.Timestamptz `json:"last_heartbeat_at"`
	LastHeartbeatAtMillis int64              `json:"last_heartbeat_at_millis"`
	AttemptKey            string             `json:"attempt_key"`
}

func (q *Queries) TouchDAGRunLease(ctx context.Context, arg TouchDAGRunLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchDAGRunLease, arg.LastHeartbeatAt, arg.LastHeartbeatAtMillis, arg.AttemptKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertActiveDistributedRun = `-- name: UpsertActiveDistributedRun :exec
INSERT INTO dagu_active_distributed_runs (
    attempt_key,
    dag_name,
    dag_run_id,
    root_dag_name,
    root_dag_run_id,
    attempt_id,
    worker_id,
    status,
    observed_at,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (attempt_key) DO UPDATE
SET dag_name = EXCLUDED.dag_name,
    dag_run_id = EXCLUDED.dag_run_id,
    root_dag_name = EXCLUDED.root_dag_name,
    root_dag_run_id = EXCLUDED.root_dag_run_id,
    attempt_id = EXCLUDED.attempt_id,
    worker_id = EXCLUDED.worker_id,
    status = EXCLUDED.status,
    observed_at = EXCLUDED.observed_at,
    data = EXCLUDED.data,
    updated_at = now()
`

type UpsertActiveDistributedRunParams struct {
	AttemptKey   string             `json:"attempt_key"`
	DagName      string             `json:"dag_name"`
	DagRunID     string             `json:"dag_run_id"`
	RootDagName  string             `json:"root_dag_name"`
	RootDagRunID string             `json:"root_dag_run_id"`
	AttemptID    string             `json:"attempt_id"`
	WorkerID     string             `json:"worker_id"`
	Status       int32              `json:"status"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	Data         []byte             `json:"data"`
}

func (q *Queries) UpsertActiveDistributedRun(ctx context.Context, arg UpsertActiveDistributedRunParams) error {
	_, err := q.db.Exec(ctx, upsertActiveDistributedRun,
		arg.AttemptKey,
		arg.DagName,
		arg.DagRunID,
		arg.RootDagName,
		arg.RootDagRunID,
		arg.AttemptID,
		arg.WorkerID,
		arg.Status,
		arg.ObservedAt,
		arg.Data,
	)
	return err
}

const upsertDAGRunLease = `-- name: UpsertDAGRunLease :exec
INSERT INTO dagu_dag_run_leases (
    attempt_key,
    dag_name,
    dag_run_id,
    root_dag_name,
    root_dag_run_id,
    attempt_id,
    queue_name,
    worker_id,
    owner_id,
    owner_host,
    owner_port,
    claimed_at,
    last_heartbeat_at,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NULLIF($9, ''),
    NULLIF($10, ''),
    $11,
    $12,
    $13,
    $14
)
ON CONFLICT (attempt_key) DO UPDATE
SET dag_name = EXCLUDED.dag_name,
    dag_run_id = EXCLUDED.dag_run_id,
    root_dag_name = EXCLUDED.root_dag_name,
    root_dag_run_id = EXCLUDED.root_dag_run_id,
    attempt_id = EXCLUDED.attempt_id,
    queue_name = EXCLUDED.queue_name,
    worker_id = EXCLUDED.worker_id,
    owner_id = EXCLUDED.owner_id,
    owner_host = EXCLUDED.owner_host,
    owner_port = EXCLUDED.owner_port,
    claimed_at = EXCLUDED.claimed_at,
    last_heartbeat_at = EXCLUDED.last_heartbeat_at,
    data = EXCLUDED.data,
    updated_at = now()
`

type UpsertDAGRunLeaseParams struct {
	AttemptKey      string             `json:"attempt_key"`
	DagName         string             `json:"dag_name"`
	DagRunID        string             `json:"dag_run_id"`
	RootDagName     string             `json:"root_dag_name"`
	RootDagRunID    string             `json:"root_dag_run_id"`
	AttemptID       string             `json:"attempt_id"`
	QueueName       string             `json:"queue_name"`
	WorkerID        string             `json:"worker_id"`
	OwnerID         interface{}        `json:"owner_id"`
	OwnerHost       interface{}        `json:"owner_host"`
	OwnerPort       pgtype.Int4        `json:"owner_port"`
	ClaimedAt       pgtype.Timestamptz `json:"claimed_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	Data            []byte             `json:"data"`
}

func (q *Queries) UpsertDAGRunLease(ctx context.Context, arg UpsertDAGRunLeaseParams) error {
	_, err := q.db.Exec(ctx, upsertDAGRunLease,
		arg.AttemptKey,
		arg.DagName,
		arg.DagRunID,
		arg.RootDagName,
		arg.RootDagRunID,
		arg.AttemptID,
		arg.QueueName,
		arg.WorkerID,
		arg.OwnerID,
		arg.OwnerHost,
		arg.OwnerPort,
		arg.ClaimedAt,
		arg.LastHeartbeatAt,
		arg.Data,
	)
	return err
}

const upsertWorkerHeartbeat = `-- name: UpsertWorkerHeartbeat :exec
INSERT INTO dagu_worker_heartbeats (
    worker_id,
    labels,
    stats,
    last_heartbeat_at,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (worker_id) DO UPDATE
SET labels = EXCLUDED.labels,
    stats = EXCLUDED.stats,
    last_heartbeat_at = EXCLUDED.last_heartbeat_at,
    data = EXCLUDED.data,
    updated_at = now()
`

type UpsertWorkerHeartbeatParams struct {
	WorkerID        string             `json:"worker_id"`
	Labels          []byte             `json:"labels"`
	Stats           []byte             `json:"stats"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	Data            []byte             `json:"data"`
}

func (q *Queries) UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, upsertWorkerHeartbeat,
		arg.WorkerID,
		arg.Labels,
		arg.Stats,
		arg.LastHeartbeatAt,
		arg.Data,
	)
	return err
}
