// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*)::integer
FROM dagu_events
WHERE (NOT $1::boolean OR kind = $2)
  AND (NOT $3::boolean OR event_type = $4)
  AND (NOT $5::boolean OR dag_name = $6)
  AND (NOT $7::boolean OR dag_run_id = $8)
  AND (NOT $9::boolean OR attempt_id = $10)
  AND (NOT $11::boolean OR session_id = $12)
  AND (NOT $13::boolean OR user_id = $14)
  AND (NOT $15::boolean OR model = $16)
  AND (NOT $17::boolean OR status = $18)
  AND (NOT $19::boolean OR occurred_at >= $20)
  AND (NOT $21::boolean OR occurred_at <= $22)
`

type CountEventsParams struct {
	HasKind      bool               `json:"has_kind"`
	Kind         string             `json:"kind"`
	HasType      bool               `json:"has_type"`
	EventType    string             `json:"event_type"`
	HasDagName   bool               `json:"has_dag_name"`
	DagName      pgtype.Text        `json:"dag_name"`
	HasDagRunID  bool               `json:"has_dag_run_id"`
	DagRunID     pgtype.Text        `json:"dag_run_id"`
	HasAttemptID bool               `json:"has_attempt_id"`
	AttemptID    pgtype.Text        `json:"attempt_id"`
	HasSessionID bool               `json:"has_session_id"`
	SessionID    pgtype.Text        `json:"session_id"`
	HasUserID    bool               `json:"has_user_id"`
	UserID       pgtype.Text        `json:"user_id"`
	HasModel     bool               `json:"has_model"`
	Model        pgtype.Text        `json:"model"`
	HasStatus    bool               `json:"has_status"`
	Status       pgtype.Text        `json:"status"`
	HasStartTime bool               `json:"has_start_time"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	HasEndTime   bool               `json:"has_end_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CountEvents(ctx context.Context, arg CountEventsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countEvents,
		arg.HasKind,
		arg.Kind,
		arg.HasType,
		arg.EventType,
		arg.HasDagName,
		arg.DagName,
		arg.HasDagRunID,
		arg.DagRunID,
		arg.HasAttemptID,
		arg.AttemptID,
		arg.HasSessionID,
		arg.SessionID,
		arg.HasUserID,
		arg.UserID,
		arg.HasModel,
		arg.Model,
		arg.HasStatus,
		arg.Status,
		arg.HasStartTime,
		arg.StartTime,
		arg.HasEndTime,
		arg.EndTime,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const emitEvent = `-- name: EmitEvent :exec
INSERT INTO dagu_events (
    id,
    event_id,
    schema_version,
    occurred_at,
    recorded_at,
    kind,
    event_type,
    source_service,
    source_instance,
    dag_name,
    dag_run_id,
    attempt_id,
    session_id,
    user_id,
    model,
    status,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NULLIF($9, ''),
    NULLIF($10, ''),
    NULLIF($11, ''),
    NULLIF($12, ''),
    NULLIF($13, ''),
    NULLIF($14, ''),
    NULLIF($15, ''),
    NULLIF($16, ''),
    $17
)
ON CONFLICT (event_id) DO NOTHING
`

type EmitEventParams struct {
	ID             uuid.UUID          `json:"id"`
	EventID        string             `json:"event_id"`
	SchemaVersion  int32              `json:"schema_version"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	Kind           string             `json:"kind"`
	EventType      string             `json:"event_type"`
	SourceService  string             `json:"source_service"`
	SourceInstance interface{}        `json:"source_instance"`
	DagName        interface{}        `json:"dag_name"`
	DagRunID       interface{}        `json:"dag_run_id"`
	AttemptID      interface{}        `json:"attempt_id"`
	SessionID      interface{}        `json:"session_id"`
	UserID         interface{}        `json:"user_id"`
	Model          interface{}        `json:"model"`
	Status         interface{}        `json:"status"`
	Data           []byte             `json:"data"`
}

func (q *Queries) EmitEvent(ctx context.Context, arg EmitEventParams) error {
	_, err := q.db.Exec(ctx, emitEvent,
		arg.ID,
		arg.EventID,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.Kind,
		arg.EventType,
		arg.SourceService,
		arg.SourceInstance,
		arg.DagName,
		arg.DagRunID,
		arg.AttemptID,
		arg.SessionID,
		arg.UserID,
		arg.Model,
		arg.Status,
		arg.Data,
	)
	return err
}

const queryEvents = `-- name: QueryEvents :many
SELECT id, event_id, schema_version, occurred_at, recorded_at, kind, event_type, source_service, source_instance, dag_name, dag_run_id, attempt_id, session_id, user_id, model, status, data_version, data, created_at
FROM dagu_events
WHERE (NOT $1::boolean OR kind = $2)
  AND (NOT $3::boolean OR event_type = $4)
  AND (NOT $5::boolean OR dag_name = $6)
  AND (NOT $7::boolean OR dag_run_id = $8)
  AND (NOT $9::boolean OR attempt_id = $10)
  AND (NOT $11::boolean OR session_id = $12)
  AND (NOT $13::boolean OR user_id = $14)
  AND (NOT $15::boolean OR model = $16)
  AND (NOT $17::boolean OR status = $18)
  AND (NOT $19::boolean OR occurred_at >= $20)
  AND (NOT $21::boolean OR occurred_at <= $22)
ORDER BY occurred_at DESC, recorded_at DESC, event_id DESC
LIMIT $24::integer
OFFSET $23::integer
`

type QueryEventsParams struct {
	HasKind      bool               `json:"has_kind"`
	Kind         string             `json:"kind"`
	HasType      bool               `json:"has_type"`
	EventType    string             `json:"event_type"`
	HasDagName   bool               `json:"has_dag_name"`
	DagName      pgtype.Text        `json:"dag_name"`
	HasDagRunID  bool               `json:"has_dag_run_id"`
	DagRunID     pgtype.Text        `json:"dag_run_id"`
	HasAttemptID bool               `json:"has_attempt_id"`
	AttemptID    pgtype.Text        `json:"attempt_id"`
	HasSessionID bool               `json:"has_session_id"`
	SessionID    pgtype.Text        `json:"session_id"`
	HasUserID    bool               `json:"has_user_id"`
	UserID       pgtype.Text        `json:"user_id"`
	HasModel     bool               `json:"has_model"`
	Model        pgtype.Text        `json:"model"`
	HasStatus    bool               `json:"has_status"`
	Status       pgtype.Text        `json:"status"`
	HasStartTime bool               `json:"has_start_time"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	HasEndTime   bool               `json:"has_end_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	RowOffset    int32              `json:"row_offset"`
	RowLimit     int32              `json:"row_limit"`
}

func (q *Queries) QueryEvents(ctx context.Context, arg QueryEventsParams) ([]DaguEvent, error) {
	rows, err := q.db.Query(ctx, queryEvents,
		arg.HasKind,
		arg.Kind,
		arg.HasType,
		arg.EventType,
		arg.HasDagName,
		arg.DagName,
		arg.HasDagRunID,
		arg.DagRunID,
		arg.HasAttemptID,
		arg.AttemptID,
		arg.HasSessionID,
		arg.SessionID,
		arg.HasUserID,
		arg.UserID,
		arg.HasModel,
		arg.Model,
		arg.HasStatus,
		arg.Status,
		arg.HasStartTime,
		arg.StartTime,
		arg.HasEndTime,
		arg.EndTime,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguEvent{}
	for rows.Next() {
		var i DaguEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.Kind,
			&i.EventType,
			&i.SourceService,
			&i.SourceInstance,
			&i.DagName,
			&i.DagRunID,
			&i.AttemptID,
			&i.SessionID,
			&i.UserID,
			&i.Model,
			&i.Status,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryEventsCursor = `-- name: QueryEventsCursor :many
SELECT id, event_id, schema_version, occurred_at, recorded_at, kind, event_type, source_service, source_instance, dag_name, dag_run_id, attempt_id, session_id, user_id, model, status, data_version, data, created_at
FROM dagu_events
WHERE (NOT $1::boolean OR kind = $2)
  AND (NOT $3::boolean OR event_type = $4)
  AND (NOT $5::boolean OR dag_name = $6)
  AND (NOT $7::boolean OR dag_run_id = $8)
  AND (NOT $9::boolean OR attempt_id = $10)
  AND (NOT $11::boolean OR session_id = $12)
  AND (NOT $13::boolean OR user_id = $14)
  AND (NOT $15::boolean OR model = $16)
  AND (NOT $17::boolean OR status = $18)
  AND (NOT $19::boolean OR occurred_at >= $20)
  AND (NOT $21::boolean OR occurred_at <= $22)
  AND (
    NOT $23::boolean
    OR (
      occurred_at,
      recorded_at,
      event_id
    ) < (
      $24::timestamptz,
      $25::timestamptz,
      $26::text
    )
  )
ORDER BY occurred_at DESC, recorded_at DESC, event_id DESC
LIMIT $27::integer
`

type QueryEventsCursorParams struct {
	HasKind         bool               `json:"has_kind"`
	Kind            string             `json:"kind"`
	HasType         bool               `json:"has_type"`
	EventType       string             `json:"event_type"`
	HasDagName      bool               `json:"has_dag_name"`
	DagName         pgtype.Text        `json:"dag_name"`
	HasDagRunID     bool               `json:"has_dag_run_id"`
	DagRunID        pgtype.Text        `json:"dag_run_id"`
	HasAttemptID    bool               `json:"has_attempt_id"`
	AttemptID       pgtype.Text        `json:"attempt_id"`
	HasSessionID    bool               `json:"has_session_id"`
	SessionID       pgtype.Text        `json:"session_id"`
	HasUserID       bool               `json:"has_user_id"`
	UserID          pgtype.Text        `json:"user_id"`
	HasModel        bool               `json:"has_model"`
	Model           pgtype.Text        `json:"model"`
	HasStatus       bool               `json:"has_status"`
	Status          pgtype.Text        `json:"status"`
	HasStartTime    bool               `json:"has_start_time"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	HasEndTime      bool               `json:"has_end_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	HasCursor       bool               `json:"has_cursor"`
	AfterOccurredAt pgtype.Timestamptz `json:"after_occurred_at"`
	AfterRecordedAt pgtype.Timestamptz `json:"after_recorded_at"`
	AfterEventID    string             `json:"after_event_id"`
	RowLimit        int32              `json:"row_limit"`
}

func (q *Queries) QueryEventsCursor(ctx context.Context, arg QueryEventsCursorParams) ([]DaguEvent, error) {
	rows, err := q.db.Query(ctx, queryEventsCursor,
		arg.HasKind,
		arg.Kind,
		arg.HasType,
		arg.EventType,
		arg.HasDagName,
		arg.DagName,
		arg.HasDagRunID,
		arg.DagRunID,
		arg.HasAttemptID,
		arg.AttemptID,
		arg.HasSessionID,
		arg.SessionID,
		arg.HasUserID,
		arg.UserID,
		arg.HasModel,
		arg.Model,
		arg.HasStatus,
		arg.Status,
		arg.HasStartTime,
		arg.StartTime,
		arg.HasEndTime,
		arg.EndTime,
		arg.HasCursor,
		arg.AfterOccurredAt,
		arg.AfterRecordedAt,
		arg.AfterEventID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguEvent{}
	for rows.Next() {
		var i DaguEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.Kind,
			&i.EventType,
			&i.SourceService,
			&i.SourceInstance,
			&i.DagName,
			&i.DagRunID,
			&i.AttemptID,
			&i.SessionID,
			&i.UserID,
			&i.Model,
			&i.Status,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
