// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DaguActiveDistributedRun struct {
	AttemptKey   string             `json:"attempt_key"`
	DagName      string             `json:"dag_name"`
	DagRunID     string             `json:"dag_run_id"`
	RootDagName  string             `json:"root_dag_name"`
	RootDagRunID string             `json:"root_dag_run_id"`
	AttemptID    string             `json:"attempt_id"`
	WorkerID     string             `json:"worker_id"`
	Status       int32              `json:"status"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	DataVersion  int32              `json:"data_version"`
	Data         []byte             `json:"data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DaguAgentSession struct {
	ID              uuid.UUID          `json:"id"`
	UserID          string             `json:"user_id"`
	DagName         pgtype.Text        `json:"dag_name"`
	Title           pgtype.Text        `json:"title"`
	Model           pgtype.Text        `json:"model"`
	ParentSessionID uuid.NullUUID      `json:"parent_session_id"`
	DelegateTask    pgtype.Text        `json:"delegate_task"`
	DataVersion     int32              `json:"data_version"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DaguAgentSessionMessage struct {
	ID          uuid.UUID          `json:"id"`
	SessionID   uuid.UUID          `json:"session_id"`
	MessageType string             `json:"message_type"`
	SequenceID  int64              `json:"sequence_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DataVersion int32              `json:"data_version"`
	Data        []byte             `json:"data"`
}

type DaguApiKey struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	KeyHash         string             `json:"key_hash"`
	KeyPrefix       string             `json:"key_prefix"`
	CreatedBy       string             `json:"created_by"`
	WorkspaceAccess []byte             `json:"workspace_access"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	DataVersion     int32              `json:"data_version"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DaguAuditEntry struct {
	ID          uuid.UUID          `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Category    string             `json:"category"`
	Action      string             `json:"action"`
	UserID      string             `json:"user_id"`
	Username    string             `json:"username"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	DataVersion int32              `json:"data_version"`
	Data        []byte             `json:"data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DaguDagRun struct {
	ID                     uuid.UUID          `json:"id"`
	DagName                string             `json:"dag_name"`
	DagRunID               string             `json:"dag_run_id"`
	RootDagName            string             `json:"root_dag_name"`
	RootDagRunID           string             `json:"root_dag_run_id"`
	IsRoot                 bool               `json:"is_root"`
	RunCreatedAt           pgtype.Timestamptz `json:"run_created_at"`
	LatestAttemptID        uuid.NullUUID      `json:"latest_attempt_id"`
	LatestAttemptCreatedAt pgtype.Timestamptz `json:"latest_attempt_created_at"`
	Workspace              sql.NullString     `json:"workspace"`
	WorkspaceValid         bool               `json:"workspace_valid"`
	Status                 pgtype.Int4        `json:"status"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	FinishedAt             pgtype.Timestamptz `json:"finished_at"`
	DataVersion            int32              `json:"data_version"`
	Data                   []byte             `json:"data"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type DaguDagRunAttempt struct {
	ID               uuid.UUID          `json:"id"`
	RunID            uuid.UUID          `json:"run_id"`
	DagName          string             `json:"dag_name"`
	DagRunID         string             `json:"dag_run_id"`
	RootDagName      string             `json:"root_dag_name"`
	RootDagRunID     string             `json:"root_dag_run_id"`
	IsRoot           bool               `json:"is_root"`
	AttemptID        string             `json:"attempt_id"`
	RunCreatedAt     pgtype.Timestamptz `json:"run_created_at"`
	AttemptCreatedAt pgtype.Timestamptz `json:"attempt_created_at"`
	Workspace        sql.NullString     `json:"workspace"`
	WorkspaceValid   bool               `json:"workspace_valid"`
	Status           pgtype.Int4        `json:"status"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	DataVersion      int32              `json:"data_version"`
	Data             []byte             `json:"data"`
	CancelRequested  bool               `json:"cancel_requested"`
	Hidden           bool               `json:"hidden"`
	LocalWorkDir     string             `json:"local_work_dir"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DaguDagRunLease struct {
	AttemptKey      string             `json:"attempt_key"`
	DagName         string             `json:"dag_name"`
	DagRunID        string             `json:"dag_run_id"`
	RootDagName     string             `json:"root_dag_name"`
	RootDagRunID    string             `json:"root_dag_run_id"`
	AttemptID       string             `json:"attempt_id"`
	QueueName       string             `json:"queue_name"`
	WorkerID        string             `json:"worker_id"`
	OwnerID         pgtype.Text        `json:"owner_id"`
	OwnerHost       pgtype.Text        `json:"owner_host"`
	OwnerPort       pgtype.Int4        `json:"owner_port"`
	ClaimedAt       pgtype.Timestamptz `json:"claimed_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	DataVersion     int32              `json:"data_version"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DaguDispatchTask struct {
	ID             uuid.UUID          `json:"id"`
	QueueName      string             `json:"queue_name"`
	AttemptKey     string             `json:"attempt_key"`
	WorkerSelector []byte             `json:"worker_selector"`
	DataVersion    int32              `json:"data_version"`
	Data           []byte             `json:"data"`
	EnqueuedAt     pgtype.Timestamptz `json:"enqueued_at"`
	ClaimToken     uuid.NullUUID      `json:"claim_token"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	ClaimExpiresAt pgtype.Timestamptz `json:"claim_expires_at"`
	WorkerID       pgtype.Text        `json:"worker_id"`
	PollerID       pgtype.Text        `json:"poller_id"`
	OwnerID        pgtype.Text        `json:"owner_id"`
	OwnerHost      pgtype.Text        `json:"owner_host"`
	OwnerPort      pgtype.Int4        `json:"owner_port"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DaguEvent struct {
	ID             uuid.UUID          `json:"id"`
	EventID        string             `json:"event_id"`
	SchemaVersion  int32              `json:"schema_version"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	Kind           string             `json:"kind"`
	EventType      string             `json:"event_type"`
	SourceService  string             `json:"source_service"`
	SourceInstance pgtype.Text        `json:"source_instance"`
	DagName        pgtype.Text        `json:"dag_name"`
	DagRunID       pgtype.Text        `json:"dag_run_id"`
	AttemptID      pgtype.Text        `json:"attempt_id"`
	SessionID      pgtype.Text        `json:"session_id"`
	UserID         pgtype.Text        `json:"user_id"`
	Model          pgtype.Text        `json:"model"`
	Status         pgtype.Text        `json:"status"`
	DataVersion    int32              `json:"data_version"`
	Data           []byte             `json:"data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DaguQueueItem struct {
	ID             uuid.UUID          `json:"id"`
	QueueName      string             `json:"queue_name"`
	Priority       int32              `json:"priority"`
	DagName        string             `json:"dag_name"`
	DagRunID       string             `json:"dag_run_id"`
	DataVersion    int32              `json:"data_version"`
	Data           []byte             `json:"data"`
	EnqueuedAt     pgtype.Timestamptz `json:"enqueued_at"`
	LeaseToken     uuid.NullUUID      `json:"lease_token"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	LeasedAt       pgtype.Timestamptz `json:"leased_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DaguServiceInstance struct {
	ServiceName     string             `json:"service_name"`
	InstanceID      string             `json:"instance_id"`
	Host            string             `json:"host"`
	Port            int32              `json:"port"`
	Status          int32              `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	DataVersion     int32              `json:"data_version"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DaguUser struct {
	ID              uuid.UUID          `json:"id"`
	Username        string             `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	AuthProvider    pgtype.Text        `json:"auth_provider"`
	OidcIssuer      pgtype.Text        `json:"oidc_issuer"`
	OidcSubject     pgtype.Text        `json:"oidc_subject"`
	IsDisabled      bool               `json:"is_disabled"`
	WorkspaceAccess []byte             `json:"workspace_access"`
	DataVersion     int32              `json:"data_version"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DaguWebhook struct {
	ID                  uuid.UUID          `json:"id"`
	DagName             string             `json:"dag_name"`
	TokenHash           string             `json:"token_hash"`
	TokenPrefix         string             `json:"token_prefix"`
	Enabled             bool               `json:"enabled"`
	AuthMode            pgtype.Text        `json:"auth_mode"`
	HmacEnforcementMode pgtype.Text        `json:"hmac_enforcement_mode"`
	CreatedBy           string             `json:"created_by"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	DataVersion         int32              `json:"data_version"`
	Data                []byte             `json:"data"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type DaguWorkerHeartbeat struct {
	WorkerID        string             `json:"worker_id"`
	Labels          []byte             `json:"labels"`
	Stats           []byte             `json:"stats"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	DataVersion     int32              `json:"data_version"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DaguWorkspace struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	DataVersion int32              `json:"data_version"`
	Data        []byte             `json:"data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
