// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queue.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ackQueueItemLease = `-- name: AckQueueItemLease :execrows
DELETE FROM dagu_queue_items
WHERE queue_name = $1
  AND lease_token = $2
`

type AckQueueItemLeaseParams struct {
	QueueName  string        `json:"queue_name"`
	LeaseToken uuid.NullUUID `json:"lease_token"`
}

func (q *Queries) AckQueueItemLease(ctx context.Context, arg AckQueueItemLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, ackQueueItemLease, arg.QueueName, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimQueueItemByID = `-- name: ClaimQueueItemByID :one
WITH picked AS (
    SELECT id
    FROM dagu_queue_items AS qi
    WHERE qi.queue_name = $5
      AND qi.id = $6
      AND (lease_token IS NULL OR lease_expires_at <= now())
    FOR UPDATE SKIP LOCKED
)
UPDATE dagu_queue_items
SET lease_token = $1,
    lease_owner = $2,
    leased_at = $3,
    lease_expires_at = $4,
    updated_at = now()
WHERE id IN (SELECT id FROM picked)
RETURNING id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
`

type ClaimQueueItemByIDParams struct {
	LeaseToken     uuid.NullUUID      `json:"lease_token"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	LeasedAt       pgtype.Timestamptz `json:"leased_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	QueueName      string             `json:"queue_name"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) ClaimQueueItemByID(ctx context.Context, arg ClaimQueueItemByIDParams) (DaguQueueItem, error) {
	row := q.db.QueryRow(ctx, claimQueueItemByID,
		arg.LeaseToken,
		arg.LeaseOwner,
		arg.LeasedAt,
		arg.LeaseExpiresAt,
		arg.QueueName,
		arg.ID,
	)
	var i DaguQueueItem
	err := row.Scan(
		&i.ID,
		&i.QueueName,
		&i.Priority,
		&i.DagName,
		&i.DagRunID,
		&i.Payload,
		&i.EnqueuedAt,
		&i.LeaseToken,
		&i.LeaseOwner,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countQueueItemsByName = `-- name: CountQueueItemsByName :one
SELECT count(*)::integer
FROM dagu_queue_items
WHERE queue_name = $1
`

func (q *Queries) CountQueueItemsByName(ctx context.Context, queueName string) (int32, error) {
	row := q.db.QueryRow(ctx, countQueueItemsByName, queueName)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteQueueItemsByDAGRun = `-- name: DeleteQueueItemsByDAGRun :many
DELETE FROM dagu_queue_items
WHERE queue_name = $1
  AND dag_name = $2
  AND dag_run_id = $3
RETURNING id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
`

type DeleteQueueItemsByDAGRunParams struct {
	QueueName string `json:"queue_name"`
	DagName   string `json:"dag_name"`
	DagRunID  string `json:"dag_run_id"`
}

func (q *Queries) DeleteQueueItemsByDAGRun(ctx context.Context, arg DeleteQueueItemsByDAGRunParams) ([]DaguQueueItem, error) {
	rows, err := q.db.Query(ctx, deleteQueueItemsByDAGRun, arg.QueueName, arg.DagName, arg.DagRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguQueueItem{}
	for rows.Next() {
		var i DaguQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.QueueName,
			&i.Priority,
			&i.DagName,
			&i.DagRunID,
			&i.Payload,
			&i.EnqueuedAt,
			&i.LeaseToken,
			&i.LeaseOwner,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteQueueItemsByIDs = `-- name: DeleteQueueItemsByIDs :many
DELETE FROM dagu_queue_items
WHERE queue_name = $1
  AND id = ANY($2::uuid[])
RETURNING id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
`

type DeleteQueueItemsByIDsParams struct {
	QueueName string      `json:"queue_name"`
	Ids       []uuid.UUID `json:"ids"`
}

func (q *Queries) DeleteQueueItemsByIDs(ctx context.Context, arg DeleteQueueItemsByIDsParams) ([]DaguQueueItem, error) {
	rows, err := q.db.Query(ctx, deleteQueueItemsByIDs, arg.QueueName, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguQueueItem{}
	for rows.Next() {
		var i DaguQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.QueueName,
			&i.Priority,
			&i.DagName,
			&i.DagRunID,
			&i.Payload,
			&i.EnqueuedAt,
			&i.LeaseToken,
			&i.LeaseOwner,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dequeueQueueItemByName = `-- name: DequeueQueueItemByName :one
WITH picked AS (
    SELECT id
    FROM dagu_queue_items AS qi
    WHERE qi.queue_name = $1
      AND (lease_token IS NULL OR lease_expires_at <= now())
    ORDER BY priority ASC, enqueued_at ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
DELETE FROM dagu_queue_items
WHERE id IN (SELECT id FROM picked)
RETURNING id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
`

func (q *Queries) DequeueQueueItemByName(ctx context.Context, queueName string) (DaguQueueItem, error) {
	row := q.db.QueryRow(ctx, dequeueQueueItemByName, queueName)
	var i DaguQueueItem
	err := row.Scan(
		&i.ID,
		&i.QueueName,
		&i.Priority,
		&i.DagName,
		&i.DagRunID,
		&i.Payload,
		&i.EnqueuedAt,
		&i.LeaseToken,
		&i.LeaseOwner,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueQueueItem = `-- name: EnqueueQueueItem :exec
INSERT INTO dagu_queue_items (
    id,
    queue_name,
    priority,
    dag_name,
    dag_run_id,
    payload,
    enqueued_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type EnqueueQueueItemParams struct {
	ID         uuid.UUID          `json:"id"`
	QueueName  string             `json:"queue_name"`
	Priority   int32              `json:"priority"`
	DagName    string             `json:"dag_name"`
	DagRunID   string             `json:"dag_run_id"`
	Payload    []byte             `json:"payload"`
	EnqueuedAt pgtype.Timestamptz `json:"enqueued_at"`
}

func (q *Queries) EnqueueQueueItem(ctx context.Context, arg EnqueueQueueItemParams) error {
	_, err := q.db.Exec(ctx, enqueueQueueItem,
		arg.ID,
		arg.QueueName,
		arg.Priority,
		arg.DagName,
		arg.DagRunID,
		arg.Payload,
		arg.EnqueuedAt,
	)
	return err
}

const listAllQueueItems = `-- name: ListAllQueueItems :many
SELECT id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
FROM dagu_queue_items
ORDER BY queue_name ASC, priority ASC, enqueued_at ASC, id ASC
`

func (q *Queries) ListAllQueueItems(ctx context.Context) ([]DaguQueueItem, error) {
	rows, err := q.db.Query(ctx, listAllQueueItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguQueueItem{}
	for rows.Next() {
		var i DaguQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.QueueName,
			&i.Priority,
			&i.DagName,
			&i.DagRunID,
			&i.Payload,
			&i.EnqueuedAt,
			&i.LeaseToken,
			&i.LeaseOwner,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueItemsByDAGName = `-- name: ListQueueItemsByDAGName :many
SELECT id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
FROM dagu_queue_items
WHERE queue_name = $1
  AND dag_name = $2
ORDER BY priority ASC, enqueued_at ASC, id ASC
`

type ListQueueItemsByDAGNameParams struct {
	QueueName string `json:"queue_name"`
	DagName   string `json:"dag_name"`
}

func (q *Queries) ListQueueItemsByDAGName(ctx context.Context, arg ListQueueItemsByDAGNameParams) ([]DaguQueueItem, error) {
	rows, err := q.db.Query(ctx, listQueueItemsByDAGName, arg.QueueName, arg.DagName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguQueueItem{}
	for rows.Next() {
		var i DaguQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.QueueName,
			&i.Priority,
			&i.DagName,
			&i.DagRunID,
			&i.Payload,
			&i.EnqueuedAt,
			&i.LeaseToken,
			&i.LeaseOwner,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueItemsByName = `-- name: ListQueueItemsByName :many
SELECT id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
FROM dagu_queue_items
WHERE queue_name = $1
ORDER BY priority ASC, enqueued_at ASC, id ASC
`

func (q *Queries) ListQueueItemsByName(ctx context.Context, queueName string) ([]DaguQueueItem, error) {
	rows, err := q.db.Query(ctx, listQueueItemsByName, queueName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguQueueItem{}
	for rows.Next() {
		var i DaguQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.QueueName,
			&i.Priority,
			&i.DagName,
			&i.DagRunID,
			&i.Payload,
			&i.EnqueuedAt,
			&i.LeaseToken,
			&i.LeaseOwner,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueItemsByNameCursor = `-- name: ListQueueItemsByNameCursor :many
SELECT id, queue_name, priority, dag_name, dag_run_id, payload, enqueued_at, lease_token, lease_owner, leased_at, lease_expires_at, created_at, updated_at
FROM dagu_queue_items
WHERE queue_name = $1
  AND (
    NOT $2::boolean
    OR (
      priority,
      enqueued_at,
      id
    ) > (
      $3::integer,
      $4::timestamptz,
      $5::uuid
    )
  )
ORDER BY priority ASC, enqueued_at ASC, id ASC
LIMIT $6::integer
`

type ListQueueItemsByNameCursorParams struct {
	QueueName       string             `json:"queue_name"`
	HasCursor       bool               `json:"has_cursor"`
	AfterPriority   int32              `json:"after_priority"`
	AfterEnqueuedAt pgtype.Timestamptz `json:"after_enqueued_at"`
	AfterID         uuid.UUID          `json:"after_id"`
	RowLimit        int32              `json:"row_limit"`
}

func (q *Queries) ListQueueItemsByNameCursor(ctx context.Context, arg ListQueueItemsByNameCursorParams) ([]DaguQueueItem, error) {
	rows, err := q.db.Query(ctx, listQueueItemsByNameCursor,
		arg.QueueName,
		arg.HasCursor,
		arg.AfterPriority,
		arg.AfterEnqueuedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguQueueItem{}
	for rows.Next() {
		var i DaguQueueItem
		if err := rows.Scan(
			&i.ID,
			&i.QueueName,
			&i.Priority,
			&i.DagName,
			&i.DagRunID,
			&i.Payload,
			&i.EnqueuedAt,
			&i.LeaseToken,
			&i.LeaseOwner,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueNames = `-- name: ListQueueNames :many
SELECT DISTINCT queue_name
FROM dagu_queue_items
ORDER BY queue_name ASC
`

func (q *Queries) ListQueueNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listQueueNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var queue_name string
		if err := rows.Scan(&queue_name); err != nil {
			return nil, err
		}
		items = append(items, queue_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseQueueItemLease = `-- name: ReleaseQueueItemLease :execrows
UPDATE dagu_queue_items
SET lease_token = NULL,
    lease_owner = NULL,
    leased_at = NULL,
    lease_expires_at = NULL,
    updated_at = now()
WHERE queue_name = $1
  AND lease_token = $2
`

type ReleaseQueueItemLeaseParams struct {
	QueueName  string        `json:"queue_name"`
	LeaseToken uuid.NullUUID `json:"lease_token"`
}

func (q *Queries) ReleaseQueueItemLease(ctx context.Context, arg ReleaseQueueItemLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseQueueItemLease, arg.QueueName, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
