// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServiceInstance = `-- name: DeleteServiceInstance :execrows
DELETE FROM dagu_service_instances
WHERE service_name = $1
  AND instance_id = $2
`

type DeleteServiceInstanceParams struct {
	ServiceName string `json:"service_name"`
	InstanceID  string `json:"instance_id"`
}

func (q *Queries) DeleteServiceInstance(ctx context.Context, arg DeleteServiceInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceInstance, arg.ServiceName, arg.InstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleServiceInstances = `-- name: DeleteStaleServiceInstances :execrows
DELETE FROM dagu_service_instances
WHERE service_name = $1
  AND last_heartbeat_at < $2
`

type DeleteStaleServiceInstancesParams struct {
	ServiceName string             `json:"service_name"`
	ActiveAfter pgtype.Timestamptz `json:"active_after"`
}

func (q *Queries) DeleteStaleServiceInstances(ctx context.Context, arg DeleteStaleServiceInstancesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleServiceInstances, arg.ServiceName, arg.ActiveAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveServiceInstances = `-- name: ListActiveServiceInstances :many
SELECT service_name, instance_id, host, port, status, started_at, last_heartbeat_at, data_version, data, created_at, updated_at
FROM dagu_service_instances
WHERE service_name = $1
  AND last_heartbeat_at >= $2
ORDER BY last_heartbeat_at DESC, instance_id ASC
`

type ListActiveServiceInstancesParams struct {
	ServiceName string             `json:"service_name"`
	ActiveAfter pgtype.Timestamptz `json:"active_after"`
}

func (q *Queries) ListActiveServiceInstances(ctx context.Context, arg ListActiveServiceInstancesParams) ([]DaguServiceInstance, error) {
	rows, err := q.db.Query(ctx, listActiveServiceInstances, arg.ServiceName, arg.ActiveAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguServiceInstance{}
	for rows.Next() {
		var i DaguServiceInstance
		if err := rows.Scan(
			&i.ServiceName,
			&i.InstanceID,
			&i.Host,
			&i.Port,
			&i.Status,
			&i.StartedAt,
			&i.LastHeartbeatAt,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchServiceInstance = `-- name: TouchServiceInstance :execrows
UPDATE dagu_service_instances
SET last_heartbeat_at = $1,
    updated_at = now()
WHERE service_name = $2
  AND instance_id = $3
`

type TouchServiceInstanceParams struct {
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	ServiceName     string             `json:"service_name"`
	InstanceID      string             `json:"instance_id"`
}

func (q *Queries) TouchServiceInstance(ctx context.Context, arg TouchServiceInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchServiceInstance, arg.LastHeartbeatAt, arg.ServiceName, arg.InstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateServiceInstanceStatus = `-- name: UpdateServiceInstanceStatus :execrows
UPDATE dagu_service_instances
SET status = $1,
    last_heartbeat_at = now(),
    updated_at = now()
WHERE service_name = $2
  AND instance_id = $3
`

type UpdateServiceInstanceStatusParams struct {
	Status      int32  `json:"status"`
	ServiceName string `json:"service_name"`
	InstanceID  string `json:"instance_id"`
}

func (q *Queries) UpdateServiceInstanceStatus(ctx context.Context, arg UpdateServiceInstanceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceInstanceStatus, arg.Status, arg.ServiceName, arg.InstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertServiceInstance = `-- name: UpsertServiceInstance :exec
INSERT INTO dagu_service_instances (
    service_name,
    instance_id,
    host,
    port,
    status,
    started_at,
    last_heartbeat_at,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (service_name, instance_id) DO UPDATE
SET host = EXCLUDED.host,
    port = EXCLUDED.port,
    status = EXCLUDED.status,
    started_at = EXCLUDED.started_at,
    last_heartbeat_at = EXCLUDED.last_heartbeat_at,
    data = EXCLUDED.data,
    updated_at = now()
`

type UpsertServiceInstanceParams struct {
	ServiceName     string             `json:"service_name"`
	InstanceID      string             `json:"instance_id"`
	Host            string             `json:"host"`
	Port            int32              `json:"port"`
	Status          int32              `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	Data            []byte             `json:"data"`
}

func (q *Queries) UpsertServiceInstance(ctx context.Context, arg UpsertServiceInstanceParams) error {
	_, err := q.db.Exec(ctx, upsertServiceInstance,
		arg.ServiceName,
		arg.InstanceID,
		arg.Host,
		arg.Port,
		arg.Status,
		arg.StartedAt,
		arg.LastHeartbeatAt,
		arg.Data,
	)
	return err
}
