// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAgentSessionMessage = `-- name: AddAgentSessionMessage :exec
INSERT INTO dagu_agent_session_messages (
    id,
    session_id,
    message_type,
    sequence_id,
    created_at,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type AddAgentSessionMessageParams struct {
	ID          uuid.UUID          `json:"id"`
	SessionID   uuid.UUID          `json:"session_id"`
	MessageType string             `json:"message_type"`
	SequenceID  int64              `json:"sequence_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Data        []byte             `json:"data"`
}

func (q *Queries) AddAgentSessionMessage(ctx context.Context, arg AddAgentSessionMessageParams) error {
	_, err := q.db.Exec(ctx, addAgentSessionMessage,
		arg.ID,
		arg.SessionID,
		arg.MessageType,
		arg.SequenceID,
		arg.CreatedAt,
		arg.Data,
	)
	return err
}

const createAgentSession = `-- name: CreateAgentSession :exec
INSERT INTO dagu_agent_sessions (
    id,
    user_id,
    dag_name,
    title,
    model,
    parent_session_id,
    delegate_task,
    data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    NULLIF($3, ''),
    NULLIF($4, ''),
    NULLIF($5, ''),
    $6,
    NULLIF($7, ''),
    $8,
    $9,
    $10
)
`

type CreateAgentSessionParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          string             `json:"user_id"`
	DagName         interface{}        `json:"dag_name"`
	Title           interface{}        `json:"title"`
	Model           interface{}        `json:"model"`
	ParentSessionID uuid.NullUUID      `json:"parent_session_id"`
	DelegateTask    interface{}        `json:"delegate_task"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAgentSession(ctx context.Context, arg CreateAgentSessionParams) error {
	_, err := q.db.Exec(ctx, createAgentSession,
		arg.ID,
		arg.UserID,
		arg.DagName,
		arg.Title,
		arg.Model,
		arg.ParentSessionID,
		arg.DelegateTask,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAgentSession = `-- name: DeleteAgentSession :execrows
DELETE FROM dagu_agent_sessions
WHERE id = $1
`

func (q *Queries) DeleteAgentSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentSession = `-- name: GetAgentSession :one
SELECT id, user_id, dag_name, title, model, parent_session_id, delegate_task, data, created_at, updated_at
FROM dagu_agent_sessions
WHERE id = $1
`

func (q *Queries) GetAgentSession(ctx context.Context, id uuid.UUID) (DaguAgentSession, error) {
	row := q.db.QueryRow(ctx, getAgentSession, id)
	var i DaguAgentSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DagName,
		&i.Title,
		&i.Model,
		&i.ParentSessionID,
		&i.DelegateTask,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestAgentSessionSequenceID = `-- name: GetLatestAgentSessionSequenceID :one
SELECT COALESCE(max(sequence_id), 0)::bigint
FROM dagu_agent_session_messages
WHERE session_id = $1
`

func (q *Queries) GetLatestAgentSessionSequenceID(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestAgentSessionSequenceID, sessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAgentSessionMessages = `-- name: ListAgentSessionMessages :many
SELECT id, session_id, message_type, sequence_id, created_at, data
FROM dagu_agent_session_messages
WHERE session_id = $1
ORDER BY sequence_id ASC, id ASC
`

func (q *Queries) ListAgentSessionMessages(ctx context.Context, sessionID uuid.UUID) ([]DaguAgentSessionMessage, error) {
	rows, err := q.db.Query(ctx, listAgentSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguAgentSessionMessage{}
	for rows.Next() {
		var i DaguAgentSessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageType,
			&i.SequenceID,
			&i.CreatedAt,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionsByUser = `-- name: ListAgentSessionsByUser :many
SELECT id, user_id, dag_name, title, model, parent_session_id, delegate_task, data, created_at, updated_at
FROM dagu_agent_sessions
WHERE user_id = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListAgentSessionsByUser(ctx context.Context, userID string) ([]DaguAgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguAgentSession{}
	for rows.Next() {
		var i DaguAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DagName,
			&i.Title,
			&i.Model,
			&i.ParentSessionID,
			&i.DelegateTask,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSubSessions = `-- name: ListAgentSubSessions :many
SELECT id, user_id, dag_name, title, model, parent_session_id, delegate_task, data, created_at, updated_at
FROM dagu_agent_sessions
WHERE parent_session_id = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListAgentSubSessions(ctx context.Context, parentSessionID uuid.NullUUID) ([]DaguAgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSubSessions, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguAgentSession{}
	for rows.Next() {
		var i DaguAgentSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DagName,
			&i.Title,
			&i.Model,
			&i.ParentSessionID,
			&i.DelegateTask,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgentSessionUpdatedAt = `-- name: TouchAgentSessionUpdatedAt :execrows
UPDATE dagu_agent_sessions
SET updated_at = $1
WHERE id = $2
`

type TouchAgentSessionUpdatedAtParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) TouchAgentSessionUpdatedAt(ctx context.Context, arg TouchAgentSessionUpdatedAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAgentSessionUpdatedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgentSession = `-- name: UpdateAgentSession :execrows
UPDATE dagu_agent_sessions
SET user_id = $1,
    dag_name = NULLIF($2, ''),
    title = NULLIF($3, ''),
    model = NULLIF($4, ''),
    parent_session_id = $5,
    delegate_task = NULLIF($6, ''),
    data = $7,
    updated_at = $8
WHERE id = $9
`

type UpdateAgentSessionParams struct {
	UserID          string             `json:"user_id"`
	DagName         interface{}        `json:"dag_name"`
	Title           interface{}        `json:"title"`
	Model           interface{}        `json:"model"`
	ParentSessionID uuid.NullUUID      `json:"parent_session_id"`
	DelegateTask    interface{}        `json:"delegate_task"`
	Data            []byte             `json:"data"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateAgentSession(ctx context.Context, arg UpdateAgentSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAgentSession,
		arg.UserID,
		arg.DagName,
		arg.Title,
		arg.Model,
		arg.ParentSessionID,
		arg.DelegateTask,
		arg.Data,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
