// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO dagu_workspaces (
    id,
    name,
    data,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateWorkspaceParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.Exec(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM dagu_workspaces
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, data_version, data, created_at, updated_at
FROM dagu_workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (DaguWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i DaguWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, data_version, data, created_at, updated_at
FROM dagu_workspaces
WHERE name = $1
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (DaguWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByName, name)
	var i DaguWorkspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DataVersion,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, data_version, data, created_at, updated_at
FROM dagu_workspaces
ORDER BY name ASC, id ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]DaguWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaguWorkspace{}
	for rows.Next() {
		var i DaguWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DataVersion,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :execrows
UPDATE dagu_workspaces
SET name = $1,
    data = $2,
    updated_at = $3
WHERE id = $4
`

type UpdateWorkspaceParams struct {
	Name      string             `json:"name"`
	Data      []byte             `json:"data"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWorkspace,
		arg.Name,
		arg.Data,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
